# Catalogo i18n generato per-schermata (it/en). Caricato da i18n.py.
EXTRA = {
"activity.empty_hint": {
"en": "Activities appear here as you work on your prospects.",
"it": "Le attività compaiono qui mentre lavori sui prospect."
},
"activity.empty_title": {
"en": "No activity yet",
"it": "Nessuna attività ancora"
},
"activity.heading": {
"en": "Activity feed",
"it": "Feed attività"
},
"activity.subtitle": {
"en": "Everything that happened with your prospects, most recent first.",
"it": "Tutto quello che è successo sui tuoi prospect, dal più recente."
},
"activity.title": {
"en": "Activity",
"it": "Attività"
},
"activity.workspace": {
"en": "Workspace",
"it": "Workspace"
},
"ask.ask": {
"en": "Ask",
"it": "Chiedi"
},
"ask.err_no_response": {
"en": "The AI engine didn't respond. Please try again.",
"it": "Il motore AI non ha risposto. Riprova."
},
"ask.example_1": {
"en": "Which are my 5 highest-priority prospects and why?",
"it": "Quali sono i miei 5 prospect a priorità più alta e perché?"
},
"ask.example_2": {
"en": "Who is in cultivation with a high ask but no recorded gifts?",
"it": "Chi è in cultivation con ask alto ma senza donazioni registrate?"
},
"ask.example_3": {
"en": "Group prospects by sector and tell me where I'm strongest",
"it": "Raggruppa i prospect per settore e dimmi dove sono più forte"
},
"ask.example_4": {
"en": "Who should I thank or follow up with?",
"it": "Chi devo ringraziare o ricontattare?"
},
"ask.example_5": {
"en": "Which foundations could I approach for my main cause?",
"it": "Quali fondazioni potrei avvicinare per la mia causa principale?"
},
"ask.hint": {
"en": "Ask a question about your prospects. The answer cites the records with clickable links.",
"it": "Fai una domanda sui tuoi prospect. La risposta cita le schede con link cliccabili."
},
"ask.input_ph": {
"en": "e.g. major donors in Lombardy not contacted in months with high affinity — give me the list and suggest the moves",
"it": "es. major donor in Lombardia non sentiti da mesi con affinità alta — fammi la lista e proponi le mosse"
},
"ask.prospect": {
"en": "prospects",
"it": "prospect"
},
"ask.stop": {
"en": "Stop",
"it": "Ferma"
},
"ask.subtitle_post": {
"en": "in natural language. Claude reads your data locally and builds lists and next moves for you.",
"it": "in linguaggio naturale. Claude legge i tuoi dati in locale e ti costruisce liste e mosse."
},
"ask.subtitle_pre": {
"en": "Query your entire CRM",
"it": "Interroga l'intero CRM"
},
"ask.title": {
"en": "Ask your data",
"it": "Chiedi ai dati"
},
"ask.workspace": {
"en": "Workspace",
"it": "Workspace"
},
"brief.ask_suggested": {
"en": "Suggested ask",
"it": "Ask consigliato"
},
"brief.breadcrumb": {
"en": "Briefing one-pager",
"it": "Briefing one-pager"
},
"brief.confirm_regenerate": {
"en": "Regenerate the briefing?",
"it": "Rigenerare il briefing?"
},
"brief.date": {
"en": "Date",
"it": "Data"
},
"brief.download_ics": {
"en": "Download .ics",
"it": "Scarica .ics"
},
"brief.duration_minutes": {
"en": "Duration (minutes)",
"it": "Durata (minuti)"
},
"brief.empty_body": {
"en": "Claude generates a one-pager with a headline, opening, 5–7 talking points, suggested ask, topics to avoid, and next steps.",
"it": "Claude genera un one-pager con headline, opening, 5-7 talking points, ask consigliato, topics da evitare, next-steps."
},
"brief.empty_title": {
"en": "No briefing yet",
"it": "Nessun briefing ancora"
},
"brief.generate": {
"en": "Generate briefing",
"it": "Genera briefing"
},
"brief.heading": {
"en": "Briefing for a call/meeting",
"it": "Briefing per call/meeting"
},
"brief.ics_hint": {
"en": "Open the file to add the event to your calendar (with a reminder 1h before).",
"it": "Apri il file per aggiungere l'evento al tuo calendario (con promemoria 1h prima)."
},
"brief.if_no": {
"en": "If it goes poorly",
"it": "Se va male"
},
"brief.if_yes": {
"en": "If it goes well",
"it": "Se va bene"
},
"brief.match_with_org": {
"en": "Match with your org",
"it": "Match con la tua org"
},
"brief.print": {
"en": "Print",
"it": "Stampa"
},
"brief.question": {
"en": "Question:",
"it": "Domanda:"
},
"brief.regenerate": {
"en": "Regenerate",
"it": "Rigenera"
},
"brief.schedule_call": {
"en": "Schedule call",
"it": "Pianifica call"
},
"brief.section_headline": {
"en": "Headline",
"it": "Headline"
},
"brief.section_opening": {
"en": "Opening",
"it": "Opening"
},
"brief.section_talking_points": {
"en": "Talking points",
"it": "Talking points"
},
"brief.subtitle": {
"en": "A strategic one-pager generated by Claude to make the most of a 30-minute meeting.",
"it": "One-pager strategico generato da Claude per gestire al meglio un incontro di 30 minuti."
},
"brief.time": {
"en": "Time",
"it": "Ora"
},
"brief.title": {
"en": "Briefing",
"it": "Briefing"
},
"brief.topics_to_avoid": {
"en": "Topics to avoid",
"it": "Topics da evitare"
},
"brief.why": {
"en": "Why:",
"it": "Perché:"
},
"chat.action_add_note": {
"en": "Add a note",
"it": "Aggiungi una nota"
},
"chat.action_change_stage": {
"en": "Change stage",
"it": "Cambia stage"
},
"chat.action_create_task": {
"en": "Create a task",
"it": "Crea un task"
},
"chat.action_write_email": {
"en": "Write an email",
"it": "Scrivi una email"
},
"chat.apply": {
"en": "Apply",
"it": "Applica"
},
"chat.breadcrumb": {
"en": "AI Chat",
"it": "Chat AI"
},
"chat.cancel": {
"en": "Cancel",
"it": "Annulla"
},
"chat.clear": {
"en": "Clear",
"it": "Pulisci"
},
"chat.clear_confirm": {
"en": "Clear the conversation?",
"it": "Pulire la conversazione?"
},
"chat.copy": {
"en": "Copy",
"it": "Copia"
},
"chat.create_task": {
"en": "Create task",
"it": "Crea task"
},
"chat.empty_before": {
"en": "Start the conversation. Claude has already read the profile of",
"it": "Inizia la conversazione. Claude ha già letto il profilo di"
},
"chat.engine_error": {
"en": "The AI engine did not respond. Please try again shortly.",
"it": "Il motore AI non ha risposto. Riprova tra poco."
},
"chat.error": {
"en": "Error",
"it": "Errore"
},
"chat.input_placeholder": {
"en": "Type a message…  (Enter to send · Shift+Enter for a new line)",
"it": "Scrivi un messaggio…  (Invio invia · Shift+Invio a capo)"
},
"chat.network_error": {
"en": "Network error",
"it": "Errore di rete"
},
"chat.new_messages": {
"en": "New messages",
"it": "Nuovi messaggi"
},
"chat.note_placeholder": {
"en": "Write a note…",
"it": "Scrivi una nota…"
},
"chat.quick_actions": {
"en": "Quick actions",
"it": "Azioni rapide"
},
"chat.response_stopped": {
"en": "Response stopped",
"it": "Risposta interrotta"
},
"chat.retry": {
"en": "Retry",
"it": "Riprova"
},
"chat.save_note": {
"en": "Save note",
"it": "Salva nota"
},
"chat.send": {
"en": "Send",
"it": "Invia"
},
"chat.stop": {
"en": "Stop the response",
"it": "Ferma la risposta"
},
"chat.suggest_angle": {
"en": "Which angle for the cause?",
"it": "Quale angolo per la causa?"
},
"chat.suggest_angle_q": {
"en": "Which angle for the main cause?",
"it": "Quale angolo per la causa principale?"
},
"chat.suggest_ask_amount": {
"en": "How much for the first ask?",
"it": "Quanto chiedergli al primo ask?"
},
"chat.suggest_ask_amount_q": {
"en": "How much should I ask for at the first ask?",
"it": "Quanto chiedergli al primo ask?"
},
"chat.suggest_cold_email": {
"en": "Cold draft, 150 words",
"it": "Bozza cold 150 parole"
},
"chat.suggest_cold_email_q": {
"en": "Write a 150-word cold email draft",
"it": "Scrivi una bozza email cold di 150 parole"
},
"chat.suggest_intro": {
"en": "Suggest an intro",
"it": "Suggerisci intro"
},
"chat.suggest_intro_q": {
"en": "Suggest a mutual connection for a cold intro",
"it": "Suggerisci una mutual connection per intro a freddo"
},
"chat.suggest_risks": {
"en": "Direct ask risks?",
"it": "Rischi ask diretto?"
},
"chat.suggest_risks_q": {
"en": "What are the risks of a direct ask now?",
"it": "Quali rischi se faccio un ask diretto ora?"
},
"chat.suggest_talking_points": {
"en": "3 talking points for the call",
"it": "3 talking points call"
},
"chat.suggest_talking_points_q": {
"en": "Write 3 talking points for the call",
"it": "Scrivi 3 talking points per la call"
},
"chat.suggestions": {
"en": "Suggestions",
"it": "Suggerimenti"
},
"chat.task_title_placeholder": {
"en": "What to do…",
"it": "Cosa fare…"
},
"chat.title": {
"en": "AI Chat",
"it": "Chat AI"
},
"chat.you": {
"en": "you",
"it": "tu"
},
"compose.back_to_prospect": {
"en": "Back to prospect",
"it": "Torna al prospect"
},
"compose.breadcrumb": {
"en": "AI Compose",
"it": "AI Compose"
},
"compose.briefing_active": {
"en": "Briefing active",
"it": "Briefing attivo"
},
"compose.briefing_missing": {
"en": "Briefing not configured",
"it": "Briefing non configurato"
},
"compose.briefing_missing_desc": {
"en": "Without context, the email will be generic.",
"it": "Senza contesto, la mail sarà generica."
},
"compose.causes": {
"en": "Causes:",
"it": "Cause:"
},
"compose.claude_writing_for": {
"en": "Claude · writing for",
"it": "Claude · scrive per"
},
"compose.configure_now": {
"en": "Configure now",
"it": "Configura ora"
},
"compose.copied": {
"en": "Copied",
"it": "Copiato"
},
"compose.copy_failed": {
"en": "Copy failed: select the text manually.",
"it": "Copia non riuscita: seleziona il testo manualmente."
},
"compose.copy_text": {
"en": "Copy text",
"it": "Copia testo"
},
"compose.draft_saved": {
"en": "Draft saved",
"it": "Bozza salvata"
},
"compose.empty_hint_post": {
"en": "The text will appear here in real time.",
"it": "Il testo apparirà qui in tempo reale."
},
"compose.empty_hint_pre": {
"en": "Fill in the settings above and click",
"it": "Compila i parametri sopra e clicca"
},
"compose.err_no_response_post": {
"en": "). Please try again shortly.",
"it": "). Riprova tra poco."
},
"compose.err_no_response_pre": {
"en": "The AI engine did not respond (code ",
"it": "Il motore AI non ha risposto (codice "
},
"compose.error": {
"en": "Error.",
"it": "Errore."
},
"compose.error_prefix": {
"en": "Error:",
"it": "Errore:"
},
"compose.generate": {
"en": "Generate draft",
"it": "Genera bozza"
},
"compose.hunter_contacts": {
"en": "Hunter contacts (click to use)",
"it": "Contatti Hunter (click per usare)"
},
"compose.key_points": {
"en": "Key points (optional)",
"it": "Punti chiave (opzionale)"
},
"compose.key_points_ph": {
"en": "E.g.: cite their talk at conference X · propose a meeting in Milan · mention the fit with cause Y",
"it": "Es: citare il suo intervento al convegno X · proporre incontro a Milano · accennare al match con causa Y"
},
"compose.manage_examples": {
"en": "+ manage examples",
"it": "+ gestisci esempi"
},
"compose.no_template": {
"en": "— None (freeform) —",
"it": "— Nessuno (libero) —"
},
"compose.open": {
"en": "open",
"it": "apri"
},
"compose.open_saved_draft": {
"en": "Open saved draft",
"it": "Apri bozza salvata"
},
"compose.optional": {
"en": "(optional)",
"it": "(opzionale)"
},
"compose.params": {
"en": "Settings",
"it": "Parametri"
},
"compose.prospect": {
"en": "Prospect",
"it": "Prospect"
},
"compose.purpose": {
"en": "Purpose",
"it": "Scopo"
},
"compose.purpose_ask": {
"en": "Donation request / direct ask",
"it": "Richiesta donazione / ask diretto"
},
"compose.purpose_briefing_meeting": {
"en": "Meeting proposal",
"it": "Proposta meeting"
},
"compose.purpose_cold_intro": {
"en": "Cold first contact",
"it": "Primo contatto a freddo"
},
"compose.purpose_custom": {
"en": "Custom (specify in key points)",
"it": "Custom (specifica nei punti chiave)"
},
"compose.purpose_event_invite": {
"en": "Event invitation",
"it": "Invito a evento"
},
"compose.purpose_introduction_request": {
"en": "Introduction request via mutual",
"it": "Richiesta intro via mutual"
},
"compose.purpose_reactivation": {
"en": "Lapsed donor reactivation",
"it": "Riattivazione lapsed donor"
},
"compose.purpose_thank_you": {
"en": "Thank you",
"it": "Ringraziamento"
},
"compose.purpose_warm_followup": {
"en": "Follow-up after interaction",
"it": "Follow-up dopo interazione"
},
"compose.recipient": {
"en": "Recipient",
"it": "Destinatario"
},
"compose.recipient_email": {
"en": "Recipient email",
"it": "Email destinatario"
},
"compose.regenerate": {
"en": "Regenerate",
"it": "Rigenera"
},
"compose.save_error": {
"en": "Save error:",
"it": "Errore salvataggio:"
},
"compose.saving": {
"en": "Saving…",
"it": "Salvataggio…"
},
"compose.status_generating": {
"en": "Generating… (usually 15–40 seconds)",
"it": "Generazione in corso… (di solito 15–40 secondi)"
},
"compose.status_interrupted": {
"en": "Generation interrupted.",
"it": "Generazione interrotta."
},
"compose.status_ready": {
"en": "Ready · review, adjust the settings, regenerate or save.",
"it": "Pronto · controlla, modifica nei parametri, rigenera o salva."
},
"compose.status_waiting": {
"en": "Waiting to generate…",
"it": "In attesa di generazione…"
},
"compose.stop": {
"en": "Stop",
"it": "Stop"
},
"compose.style_example": {
"en": "Style example (optional)",
"it": "Esempio di stile (opzionale)"
},
"compose.style_help": {
"en": "Claude mirrors the register, rhythm and structure of the example. The content is rewritten for THIS prospect.",
"it": "Claude imita registro, ritmo e struttura dell'esempio. Il contenuto viene riscritto per QUESTO prospect."
},
"compose.subject": {
"en": "Subject",
"it": "Oggetto"
},
"compose.subject_prefix": {
"en": "Subject: ",
"it": "Oggetto: "
},
"compose.subtitle": {
"en": "Claude writes in real time — watch the text unfold. Then save or regenerate.",
"it": "Claude scrive in tempo reale, vedi il testo srotolarsi. Poi salva o rigenera."
},
"compose.title": {
"en": "Draft an email",
"it": "Genera bozza email"
},
"compose.tone": {
"en": "Tone",
"it": "Tono"
},
"compose.tone_confidential": {
"en": "Confidential, intimate",
"it": "Confidenziale, intimo"
},
"compose.tone_direct": {
"en": "Direct, concise",
"it": "Diretto, asciutto"
},
"compose.tone_formal": {
"en": "Formal, institutional",
"it": "Formale istituzionale"
},
"compose.tone_visionary": {
"en": "Visionary, narrative",
"it": "Visionario, narrativo"
},
"compose.tone_warm": {
"en": "Warm, personal",
"it": "Caloroso, personale"
},
"compose.word_target": {
"en": "Length (words)",
"it": "Lunghezza (parole)"
},
"compose.words": {
"en": "words",
"it": "parole"
},
"dash.active_ai_research": {
"en": "Active AI research",
"it": "Ricerche AI attive"
},
"dash.all": {
"en": "All →",
"it": "Tutti →"
},
"dash.all_caught_up": {
"en": "All caught up",
"it": "Tutto in pari"
},
"dash.all_tasks": {
"en": "All tasks →",
"it": "Tutti i task →"
},
"dash.briefing_active": {
"en": "Briefing active",
"it": "Briefing attivo"
},
"dash.causes": {
"en": "Cause areas:",
"it": "Cause:"
},
"dash.col_capacity": {
"en": "Capacity",
"it": "Capacity"
},
"dash.col_propensity": {
"en": "Propensity",
"it": "Propensity"
},
"dash.col_prospect": {
"en": "Prospect",
"it": "Prospect"
},
"dash.col_stage": {
"en": "Stage",
"it": "Stage"
},
"dash.corporate": {
"en": "corporate",
"it": "corporate"
},
"dash.create_goal": {
"en": "Create goal",
"it": "Crea goal"
},
"dash.create_task": {
"en": "Create task",
"it": "Crea task"
},
"dash.forecast_pipeline": {
"en": "pipeline forecast",
"it": "forecast pipeline"
},
"dash.foundations": {
"en": "foundations",
"it": "fondazioni"
},
"dash.goals": {
"en": "Goals",
"it": "Goals"
},
"dash.kpi_overdue_tasks": {
"en": "Overdue tasks",
"it": "Task scaduti"
},
"dash.kpi_raised": {
"en": "Raised",
"it": "Raccolto"
},
"dash.kpi_raised_tip": {
"en": "Gifts actually received this year + weighted forecast of the open pipeline.",
"it": "Donazioni realmente incassate quest'anno + forecast pesato della pipeline aperta."
},
"dash.kpi_running_jobs": {
"en": "Jobs running",
"it": "Job in corso"
},
"dash.kpi_total_prospects": {
"en": "Total prospects",
"it": "Prospect totali"
},
"dash.major_donor": {
"en": "major donors",
"it": "major donor"
},
"dash.manage": {
"en": "Manage →",
"it": "Gestisci →"
},
"dash.mark_thanked": {
"en": "Mark as thanked",
"it": "Segna ringraziato"
},
"dash.new_prospect": {
"en": "New prospect",
"it": "Nuovo prospect"
},
"dash.no_activity": {
"en": "No activity",
"it": "Nessuna attività"
},
"dash.no_date": {
"en": "no date",
"it": "senza data"
},
"dash.no_goals": {
"en": "No goals defined",
"it": "Nessun obiettivo definito"
},
"dash.no_prospects": {
"en": "No prospects yet",
"it": "Nessun prospect ancora"
},
"dash.no_prospects_desc": {
"en": "Run your first AI search.",
"it": "Avvia la prima ricerca AI."
},
"dash.no_tasks_today": {
"en": "No tasks for today",
"it": "Nessun task per oggi"
},
"dash.open_article": {
"en": "Open article",
"it": "Apri articolo"
},
"dash.opportunity": {
"en": "opportunity",
"it": "opportunità"
},
"dash.org_setup_desc": {
"en": "Without a briefing, Claude works blind. Add your mission, cause areas, ask tiers and ideal donor profile → every search becomes 10× more relevant.",
"it": "Senza briefing Claude lavora alla cieca. Aggiungi mission, cause, tier ask, profilo donor ideale → ogni ricerca diventa 10× più rilevante."
},
"dash.org_setup_title": {
"en": "Set up your organization context",
"it": "Configura il contesto della tua organizzazione"
},
"dash.outlook_note": {
"en": "Outlook = actual raised + weighted pipeline forecast (overall, not per single goal).",
"it": "Outlook = raccolto reale + forecast pesato della pipeline (complessivo, non per singolo obiettivo)."
},
"dash.pipeline_desc": {
"en": "Prospect count and total ask amount",
"it": "Conteggio prospect e somma ask amount"
},
"dash.pipeline_title": {
"en": "Pipeline by stage",
"it": "Pipeline per stadio"
},
"dash.promised": {
"en": "pledged",
"it": "promesso"
},
"dash.recent_activity": {
"en": "Recent activity",
"it": "Attività recenti"
},
"dash.recover_now": {
"en": "Catch up now →",
"it": "Da recuperare subito →"
},
"dash.see_all": {
"en": "See all →",
"it": "Vedi tutti →"
},
"dash.signals_desc": {
"en": "Favorable moments to make the ask, from your prospects' news",
"it": "Momenti favorevoli per l'ask, dalle news dei tuoi prospect"
},
"dash.signals_title": {
"en": "Recent signals",
"it": "Segnali recenti"
},
"dash.start_research": {
"en": "Start research",
"it": "Avvia ricerca"
},
"dash.subtitle": {
"en": "Overview of your major donor & corporate pipeline",
"it": "Panoramica della pipeline major donor & corporate"
},
"dash.tasks_today_desc": {
"en": "Things to close now — open, overdue, no date",
"it": "Cose da chiudere ora — apri, scadute, senza data"
},
"dash.tasks_today_title": {
"en": "Tasks for today",
"it": "Task per oggi"
},
"dash.thank_desc": {
"en": "Gifts received but not yet acknowledged — thank within 48-72h",
"it": "Donazioni incassate ancora senza ringraziamento — falli entro 48-72h"
},
"dash.thank_title": {
"en": "To thank",
"it": "Da ringraziare"
},
"dash.title": {
"en": "Dashboard",
"it": "Dashboard"
},
"dash.top_prospects_desc": {
"en": "AI score + capacity rating",
"it": "Score AI + capacity rating"
},
"dash.top_prospects_title": {
"en": "Top prospects by propensity",
"it": "Top prospect per propensity"
},
"dash.workspace": {
"en": "Workspace",
"it": "Workspace"
},
"draft.act_expand": {
"en": "Expand",
"it": "Espandi"
},
"draft.act_fix_grammar": {
"en": "Fix grammar",
"it": "Correggi grammatica"
},
"draft.act_fundraiser": {
"en": "Rewrite as a senior fundraiser",
"it": "Riscrivi come fundraiser senior"
},
"draft.act_more_direct": {
"en": "More direct",
"it": "Più diretto"
},
"draft.act_more_formal": {
"en": "More formal",
"it": "Più formale"
},
"draft.act_more_intimate": {
"en": "More intimate",
"it": "Più intimo"
},
"draft.act_more_visionary": {
"en": "More visionary",
"it": "Più visionario"
},
"draft.act_rephrase": {
"en": "Rephrase",
"it": "Riformula"
},
"draft.act_shorten": {
"en": "Shorten",
"it": "Accorcia"
},
"draft.act_simplify": {
"en": "Simplify language",
"it": "Semplifica linguaggio"
},
"draft.act_softer": {
"en": "Softer",
"it": "Più morbido"
},
"draft.act_translate_en": {
"en": "Translate to English",
"it": "Traduci in inglese"
},
"draft.act_translate_fr": {
"en": "Translate to French",
"it": "Traduci in francese"
},
"draft.act_warmer": {
"en": "Warmer",
"it": "Più caloroso"
},
"draft.actions": {
"en": "actions",
"it": "azioni"
},
"draft.ai_continuing": {
"en": "Claude is continuing…",
"it": "Claude continua…"
},
"draft.ai_menu": {
"en": "AI menu",
"it": "menu AI"
},
"draft.ai_rewriting": {
"en": "Claude is rewriting…",
"it": "Claude sta riscrivendo…"
},
"draft.applied": {
"en": "applied",
"it": "applicato"
},
"draft.ask_claude_about": {
"en": "Ask Claude about",
"it": "Chiedi a Claude su"
},
"draft.bm_direct": {
"en": "+ Direct",
"it": "+ Diretto"
},
"draft.bm_warmer": {
"en": "+ Warmer",
"it": "+ Caloroso"
},
"draft.breadcrumb": {
"en": "Email editor",
"it": "Editor email"
},
"draft.confirm_delete": {
"en": "Delete draft?",
"it": "Eliminare bozza?"
},
"draft.continue": {
"en": "Continue",
"it": "Continua"
},
"draft.delete": {
"en": "Delete",
"it": "Elimina"
},
"draft.editor_ph": {
"en": "Write here… type / for AI actions",
"it": "Scrivi qui… digita / per le azioni AI"
},
"draft.email": {
"en": "Email",
"it": "Email"
},
"draft.error": {
"en": "Error",
"it": "Errore"
},
"draft.error_prefix": {
"en": "Error:",
"it": "Errore:"
},
"draft.flash_add_email": {
"en": "Add the recipient's email",
"it": "Aggiungi l'email del destinatario"
},
"draft.flash_continued": {
"en": "Continued",
"it": "Continuato"
},
"draft.flash_draft_saved": {
"en": "Draft saved",
"it": "Bozza salvata"
},
"draft.flash_no_email_copied": {
"en": "No recipient email: text copied to clipboard",
"it": "Nessuna email destinatario: testo copiato negli appunti"
},
"draft.flash_select_first": {
"en": "Select the text first",
"it": "Seleziona prima il testo"
},
"draft.flash_snippet_saved": {
"en": "Snippet saved",
"it": "Snippet salvato"
},
"draft.flash_subject_applied": {
"en": "Subject applied",
"it": "Oggetto applicato"
},
"draft.flash_write_first": {
"en": "Write something first",
"it": "Scrivi qualcosa prima"
},
"draft.gen_5_variants": {
"en": "Generate 5 variants",
"it": "Genera 5 varianti"
},
"draft.generating_subjects": {
"en": "Generating 5 subjects…",
"it": "Genero 5 oggetti…"
},
"draft.live_stats": {
"en": "Live stats",
"it": "Live stats"
},
"draft.mailto_title_missing": {
"en": "Add the recipient's email to open the client",
"it": "Aggiungi l'email del destinatario per aprire il client"
},
"draft.mailto_title_ok": {
"en": "Opens the email in your client",
"it": "Apre la mail nel tuo client"
},
"draft.mark_sent": {
"en": "Mark as sent",
"it": "Segna inviata"
},
"draft.min_read": {
"en": "min read",
"it": "min lettura"
},
"draft.no_snippets": {
"en": "No snippets",
"it": "Nessuno snippet"
},
"draft.no_subject": {
"en": "No subject",
"it": "Senza oggetto"
},
"draft.no_subject_paren": {
"en": "(no subject)",
"it": "(senza oggetto)"
},
"draft.open_in_client": {
"en": "Open in client",
"it": "Apri in client"
},
"draft.preview": {
"en": "Preview",
"it": "Anteprima"
},
"draft.prompt_snippet_name": {
"en": "Snippet name:",
"it": "Nome dello snippet:"
},
"draft.prospect": {
"en": "Prospect",
"it": "Prospect"
},
"draft.q_formal": {
"en": "+ Formal",
"it": "+ Formale"
},
"draft.q_improve": {
"en": "Improve",
"it": "Migliora"
},
"draft.q_longer": {
"en": "+50% length",
"it": "+50% lungh."
},
"draft.q_shorter": {
"en": "−50% length",
"it": "−50% lungh."
},
"draft.q_visionary": {
"en": "+ Visionary",
"it": "+ Visionario"
},
"draft.recipient": {
"en": "Recipient",
"it": "Destinatario"
},
"draft.save_changes": {
"en": "Save changes",
"it": "Salva modifiche"
},
"draft.save_failed": {
"en": "Save failed — use \"Save changes\"",
"it": "Salvataggio non riuscito — usa \"Salva modifiche\""
},
"draft.save_selection_snippet": {
"en": "Save selection as snippet",
"it": "Salva selezione come snippet"
},
"draft.saved_at": {
"en": "Saved at",
"it": "Salvato alle"
},
"draft.saving": {
"en": "Saving…",
"it": "Salvataggio…"
},
"draft.sent": {
"en": "Sent",
"it": "Inviata"
},
"draft.slash_cleanup": {
"en": "AI · cleanup",
"it": "AI · pulizia"
},
"draft.slash_language": {
"en": "AI · language",
"it": "AI · lingua"
},
"draft.slash_style": {
"en": "AI · style",
"it": "AI · stile"
},
"draft.slash_tone": {
"en": "AI · tone",
"it": "AI · tono"
},
"draft.snippet_search_ph": {
"en": "Search snippets…",
"it": "Cerca snippet…"
},
"draft.stat_chars": {
"en": "Characters",
"it": "Caratteri"
},
"draft.stat_reading": {
"en": "Reading",
"it": "Lettura"
},
"draft.stat_words": {
"en": "Words",
"it": "Parole"
},
"draft.subject": {
"en": "Subject",
"it": "Oggetto"
},
"draft.subject_ph": {
"en": "Email subject…",
"it": "Oggetto email…"
},
"draft.subject_prefix": {
"en": "Subject: ",
"it": "Oggetto: "
},
"draft.transform_all": {
"en": "Transform all",
"it": "Trasforma tutto"
},
"draft.tt_bold": {
"en": "Bold (⌘B)",
"it": "Grassetto (⌘B)"
},
"draft.tt_bullet_list": {
"en": "Bullet list",
"it": "Elenco puntato"
},
"draft.tt_continue": {
"en": "Continue writing (AI)",
"it": "Continua scrittura (AI)"
},
"draft.tt_italic": {
"en": "Italic (⌘I)",
"it": "Corsivo (⌘I)"
},
"draft.tt_numbered_list": {
"en": "Numbered list",
"it": "Elenco numerato"
},
"draft.tt_snippets": {
"en": "Snippets",
"it": "Snippet"
},
"draft.tt_underline": {
"en": "Underline",
"it": "Sottolineato"
},
"draft.unknown": {
"en": "unknown",
"it": "sconosciuto"
},
"draft.unsaved_changes": {
"en": "Unsaved changes…",
"it": "Modifiche non salvate…"
},
"draft.words": {
"en": "words",
"it": "parole"
},
"dup.candidate_groups": {
"en": "candidate groups",
"it": "gruppi candidati"
},
"dup.confirm_merge": {
"en": "Confirm the merge? Prospects not selected as master will be deleted and their data moved into the master.",
"it": "Confermi il merge? I prospect non selezionati come master verranno eliminati e i loro dati spostati nel master."
},
"dup.created": {
"en": "Created",
"it": "Creato"
},
"dup.empty_body": {
"en": "Your CRM is clean. Nice work.",
"it": "Il CRM è pulito. Buon lavoro."
},
"dup.empty_title": {
"en": "No suspected duplicates",
"it": "Nessun duplicato sospetto"
},
"dup.master": {
"en": "Master",
"it": "Master"
},
"dup.merge_into": {
"en": "Merge",
"it": "Unisci"
},
"dup.merge_note": {
"en": "Merging moves all child data (gifts, activity, tags, news, sources) into the chosen master.",
"it": "Il merge sposta tutti i dati child (donazioni, attività, tag, news, fonti) nel master scelto."
},
"dup.prospect": {
"en": "prospects",
"it": "prospect"
},
"dup.run_merge": {
"en": "Run merge",
"it": "Esegui merge"
},
"dup.subtitle": {
"en": "Merge candidates found by email, LinkedIn, domain or similar name. Choose which prospect to keep as the master and which ones to merge into it.",
"it": "Candidati merge trovati per email, LinkedIn, dominio o nome simile. Scegli quale prospect tenere come master e quali unire in esso."
},
"dup.title": {
"en": "Duplicates",
"it": "Duplicati"
},
"dup.updated": {
"en": "updated",
"it": "aggiornato"
},
"etpl.body": {
"en": "Full email body",
"it": "Corpo email completo"
},
"etpl.body_ph": {
"en": "Subject: …\n\nDear …,\n\n[the full text of your email to use as a style reference]",
"it": "Oggetto: …\n\nCaro/a …,\n\n[testo completo della tua email che vuoi usare come riferimento di stile]"
},
"etpl.category": {
"en": "Category",
"it": "Categoria"
},
"etpl.confirm_delete": {
"en": "Delete this template?",
"it": "Eliminare questo template?"
},
"etpl.delete": {
"en": "Delete",
"it": "Elimina"
},
"etpl.description": {
"en": "Description (why it works)",
"it": "Descrizione (perché funziona)"
},
"etpl.description_ph": {
"en": "e.g. direct tone, ask at the close, cites a concrete match",
"it": "Es: tono diretto, ask in chiusura, cita match concreto"
},
"etpl.empty_body": {
"en": "Upload a past email of yours that works well. Then select it in AI Compose and Claude will use it as a style reference.",
"it": "Carica una tua email passata che funziona bene. Poi nell'AI Compose la scegli e Claude la userà come riferimento di stile."
},
"etpl.empty_title": {
"en": "No samples yet",
"it": "Nessun esempio ancora"
},
"etpl.name": {
"en": "Name",
"it": "Nome"
},
"etpl.name_ph": {
"en": "e.g. Cold ask, 200 words",
"it": "Es: Cold ask 200 parole"
},
"etpl.new": {
"en": "New sample",
"it": "Nuovo esempio"
},
"etpl.save": {
"en": "Save changes",
"it": "Salva modifiche"
},
"etpl.save_example": {
"en": "Save sample",
"it": "Salva esempio"
},
"etpl.subtitle": {
"en": "Upload samples of your best outreach emails. When you generate a draft with AI Compose, pick a sample from the dropdown: Claude will mirror its tone, rhythm and structure while adapting the content to the prospect.",
"it": "Carica esempi delle tue migliori email di contatto. Quando generi una bozza con AI Compose, scegli un esempio dal menu a tendina: Claude imiterà registro, ritmo e struttura adattando il contenuto al prospect."
},
"etpl.title": {
"en": "Email samples",
"it": "Esempi di email"
},
"goals.active_goals": {
"en": "Active goals",
"it": "Obiettivi attivi"
},
"goals.active_goals_hint": {
"en": "Overall outlook compared against each goal",
"it": "Outlook complessivo confrontato con ogni obiettivo"
},
"goals.archive": {
"en": "Archive →",
"it": "Archivia →"
},
"goals.create_goal": {
"en": "Create goal",
"it": "Crea obiettivo"
},
"goals.empty": {
"en": "No goals yet. Create one to track your fundraising.",
"it": "Nessun obiettivo. Creane uno per tracciare la raccolta."
},
"goals.forecast_weighted": {
"en": "Weighted forecast",
"it": "Forecast pesato"
},
"goals.forecast_weighted_tip": {
"en": "Expected value of the open pipeline, weighted by each stage's conversion probability.",
"it": "Valore atteso della pipeline aperta, pesato per la probabilità di conversione di ogni stadio."
},
"goals.gross_potential": {
"en": "gross potential",
"it": "potenziale lordo"
},
"goals.label": {
"en": "Label",
"it": "Label"
},
"goals.label_ph": {
"en": "e.g. Year-end campaign 2026",
"it": "es. Campagna fine vita 2026"
},
"goals.new_goal": {
"en": "New goal",
"it": "Nuovo obiettivo"
},
"goals.notes": {
"en": "Notes",
"it": "Note"
},
"goals.on": {
"en": "of",
"it": "su"
},
"goals.outlook": {
"en": "Outlook",
"it": "Outlook"
},
"goals.outlook_desc": {
"en": "Raised + weighted forecast",
"it": "Raccolto + forecast pesato"
},
"goals.period": {
"en": "Period",
"it": "Periodo"
},
"goals.period_ph": {
"en": "2026 / Q1 / Campaign…",
"it": "2026 / Q1 / Campagna…"
},
"goals.promised": {
"en": "pledged",
"it": "promesso"
},
"goals.raised_received": {
"en": "Raised (received)",
"it": "Raccolto (incassato)"
},
"goals.raised_tip": {
"en": "Gifts actually received (gift table).",
"it": "Donazioni realmente incassate (tabella gift)."
},
"goals.real_donations": {
"en": "actual gifts",
"it": "donazioni reali"
},
"goals.subtitle": {
"en": "Set fundraising goals and compare them against what's raised + the weighted pipeline forecast.",
"it": "Definisci obiettivi di raccolta e confrontali con l'acquisito + il forecast pesato della pipeline."
},
"goals.target_eur": {
"en": "Target EUR",
"it": "Target EUR"
},
"goals.title": {
"en": "Goals & forecast",
"it": "Goals & forecast"
},
"goals.tools": {
"en": "Tools",
"it": "Strumenti"
},
"goals.year": {
"en": "Year",
"it": "Anno"
},
"import.btn_import": {
"en": "Import",
"it": "Importa"
},
"import.example": {
"en": "Example",
"it": "Esempio"
},
"import.field_default_type": {
"en": "Default type",
"it": "Tipo di default"
},
"import.field_default_type_help": {
"en": "Used when the \"type\" column is missing from the CSV.",
"it": "Usato se la colonna \"type\" non è presente nel CSV."
},
"import.field_file": {
"en": "CSV file",
"it": "File CSV"
},
"import.field_file_help": {
"en": "Separator: comma, semicolon or tab (auto-detected). UTF-8 encoding recommended.",
"it": "Separatore: virgola, punto-e-virgola o tab (auto-detected). Encoding UTF-8 raccomandato."
},
"import.headers_title": {
"en": "Recognized CSV headers",
"it": "Header CSV riconosciuti"
},
"import.opt_corporate": {
"en": "Corporate (company/foundation)",
"it": "Corporate (azienda/foundation)"
},
"import.opt_individual": {
"en": "Individual (major donor)",
"it": "Individual (major donor)"
},
"import.required": {
"en": "(required)",
"it": "(obbligatorio)"
},
"import.run_each": {
"en": "Run research on each one",
"it": "Avvia ricerca su ciascuno"
},
"import.run_each_desc": {
"en": "For every imported row, queues an AI research. Note: 1 Claude call per row.",
"it": "Per ogni riga importata, mette in coda una ricerca AI. Attenzione: 1 chiamata Claude per riga."
},
"import.subtitle": {
"en": "Upload a list of prospects (e.g. from Excel) and — optionally — start AI research for each one right away.",
"it": "Carica una lista di prospect (es. da Excel) e — opzionalmente — avvia subito la ricerca AI per ognuno."
},
"import.tip_1": {
"en": "Start with a small batch (10-20 rows) to validate the format.",
"it": "Inizia con un batch piccolo (10-20 righe) per validare il formato."
},
"import.tip_2": {
"en": "Without AI research: instant import, \"empty\" profiles to enrich later.",
"it": "Senza ricerca AI: import istantaneo, profili \"vuoti\" da arricchire dopo."
},
"import.tip_3": {
"en": "With AI research: 1-3 min per row, Claude works through the queue.",
"it": "Con ricerca AI: 1-3 min per riga, Claude lavora in coda."
},
"import.tip_4": {
"en": "Duplicates: no automatic dedup, manual review required.",
"it": "Duplicati: non c'è dedup automatico, controllo a vista."
},
"import.tips": {
"en": "Tips",
"it": "Suggerimenti"
},
"import.title": {
"en": "Import CSV",
"it": "Import CSV"
},
"import.tools": {
"en": "Tools",
"it": "Strumenti"
},
"net.cita_come": {
"en": "cites them as:",
"it": "lo cita come:"
},
"net.connessione": {
"en": "connection",
"it": "connessione"
},
"net.empty_incoming": {
"en": "No inbound citations",
"it": "Nessuna citazione inbound"
},
"net.empty_outgoing": {
"en": "No connections mapped",
"it": "Nessuna connessione mappata"
},
"net.incoming": {
"en": "Cited as a connection by",
"it": "Citato come connessione da"
},
"net.nel_crm": {
"en": "in CRM",
"it": "nel CRM"
},
"net.network": {
"en": "Network",
"it": "Network"
},
"net.network_di": {
"en": "Network of",
"it": "Network di"
},
"net.outgoing": {
"en": "Outgoing connections",
"it": "Connessioni in uscita"
},
"net.subtitle_post": {
"en": "among their connections)",
"it": "tra le sue connessioni)"
},
"net.subtitle_pre": {
"en": "Outgoing connections (who they know) and inbound ones (who cites",
"it": "Connessioni in uscita (chi conosce) e in entrata (chi cita"
},
"netg.cerca_nome": {
"en": "Search name…",
"it": "Cerca nome…"
},
"netg.collegamenti": {
"en": "links",
"it": "collegamenti"
},
"netg.empty_affiliazioni": {
"en": "affiliations",
"it": "affiliazioni"
},
"netg.empty_board": {
"en": "boards",
"it": "board"
},
"netg.empty_erogazioni": {
"en": "grants",
"it": "erogazioni"
},
"netg.empty_mid1": {
"en": ", the",
"it": ", dai"
},
"netg.empty_mid2": {
"en": "and the",
"it": "e dalle"
},
"netg.empty_mid3": {
"en": "found by AI research. Run or update a search, then click",
"it": "trovate dalla ricerca AI. Esegui o aggiorna una ricerca, poi clicca"
},
"netg.empty_pre": {
"en": "No links yet. Edges come from the",
"it": "Nessun collegamento ancora. Gli archi nascono dalle"
},
"netg.entita_citate": {
"en": "cited entities",
"it": "entità citate"
},
"netg.entities_title": {
"en": "Beyond prospects and foundations, also show cited partners and trade associations",
"it": "Oltre a prospect e fondazioni, mostra anche partner e associazioni di categoria citati"
},
"netg.filtra": {
"en": "Filter:",
"it": "Filtra:"
},
"netg.hint": {
"en": "Hover over a node to isolate its links · Scroll = zoom · Drag = move · Click = open profile",
"it": "Passa il mouse su un nodo per isolarne i collegamenti · Scroll = zoom · Drag = sposta · Click = apri scheda"
},
"netg.js_edge_board": {
"en": "Affiliation / board",
"it": "Affiliazione / board"
},
"netg.js_edge_connection": {
"en": "Connection",
"it": "Connessione"
},
"netg.js_edge_giving": {
"en": "Funds / donates",
"it": "Finanzia / dona"
},
"netg.js_entita": {
"en": "entities",
"it": "entità"
},
"netg.js_ext_contacts": {
"en": "people/contacts not in CRM",
"it": "persone/contatti non nel CRM"
},
"netg.js_lib_error": {
"en": "Visualization library not loaded.",
"it": "Libreria di visualizzazione non caricata."
},
"netg.js_lib_error2": {
"en": "Check your connection and reload the page.",
"it": "Verifica la connessione e ricarica la pagina."
},
"netg.js_no_prospect": {
"en": "No prospects yet.",
"it": "Nessun prospect ancora."
},
"netg.js_prospect": {
"en": "prospects",
"it": "prospect"
},
"netg.js_start_research": {
"en": "Start a search",
"it": "Inizia una ricerca"
},
"netg.js_visibili": {
"en": "visible",
"it": "visibili"
},
"netg.legend_corporate": {
"en": "Corporate",
"it": "Corporate"
},
"netg.legend_entity": {
"en": "cited entity",
"it": "ente citato"
},
"netg.legend_foundation": {
"en": "Foundation",
"it": "Fondazione"
},
"netg.legend_major": {
"en": "Major donor",
"it": "Major donor"
},
"netg.mostra_enti": {
"en": "Show all cited entities",
"it": "Mostra tutti gli enti citati"
},
"netg.prospect": {
"en": "prospects",
"it": "prospect"
},
"netg.relink": {
"en": "Relink",
"it": "Ricollega"
},
"netg.relink_busy": {
"en": "Relinking…",
"it": "Ricollego…"
},
"netg.relink_confirm": {
"en": "Recalculate all internal connections with the updated matching?",
"it": "Ricalcolare tutte le connessioni interne con il matching aggiornato?"
},
"netg.solo_collegati": {
"en": "Connected only",
"it": "Solo collegati"
},
"netg.subtitle": {
"en": "Prospects, foundations and entities linked by affiliations, boards and grants. Click a prospect to open it.",
"it": "Prospect, fondazioni ed enti collegati da affiliazioni, board ed erogazioni. Click su un prospect per aprirlo."
},
"netg.title": {
"en": "Network map",
"it": "Network mappa"
},
"netg.tutti_stage": {
"en": "All stages",
"it": "Tutti gli stage"
},
"netg.tutti_tipi": {
"en": "All types",
"it": "Tutti i tipi"
},
"org.breadcrumb": {
"en": "Workspace · Configuration",
"it": "Workspace · Configurazione"
},
"org.briefing_claude": {
"en": "Claude briefing",
"it": "Briefing Claude"
},
"org.briefing_placeholder": {
"en": "Without context Claude works \"blind\". With a good briefing, every search becomes targeted: capacity estimated against your tiers, propensity calibrated to your causes, next-best-action citing your real campaigns.",
"it": "Senza contesto Claude lavora \"alla cieca\". Con un buon briefing, ogni ricerca diventa mirata: capacity stimata sui tuoi tier, propensity calibrata sulle tue cause, next-best-action che cita le tue campagne reali."
},
"org.configure_org": {
"en": "Configure your organization",
"it": "Configura la tua organizzazione"
},
"org.f_annual_budget": {
"en": "Annual budget (descriptive)",
"it": "Budget annuo (descrittivo)"
},
"org.f_annual_budget_eur": {
"en": "Annual budget (EUR, number)",
"it": "Budget annuo (EUR, numero)"
},
"org.f_annual_budget_ph": {
"en": "e.g. 1.2M EUR (2024)",
"it": "es. 1.2M EUR (2024)"
},
"org.f_ask_corporate": {
"en": "Typical corporate ask (EUR)",
"it": "Ask tipico corporate (EUR)"
},
"org.f_ask_individual": {
"en": "Typical individual ask (EUR)",
"it": "Ask tipico individual (EUR)"
},
"org.f_beneficiaries": {
"en": "Beneficiaries",
"it": "Beneficiari"
},
"org.f_beneficiaries_ph": {
"en": "Whom you serve, how many people, in what way.",
"it": "Chi servite, in quante persone, in che modo."
},
"org.f_campaigns": {
"en": "Recent campaigns",
"it": "Campagne recenti"
},
"org.f_campaigns_ph": {
"en": "Liberi tutti, Legal Euthanasia, 5x1000 2024, Milan benefit gala…",
"it": "Liberi tutti, Eutanasia Legale, 5x1000 2024, gala benefit Milano…"
},
"org.f_cause_areas": {
"en": "Causes / themes (comma-separated)",
"it": "Cause / temi (separati da virgola)"
},
"org.f_cause_areas_hint": {
"en": "→ Those who have donated to/supported similar causes in the past will get a higher affinity score.",
"it": "→ Chi nel suo passato ha donato/sostenuto cause simili otterrà un affinity score più alto."
},
"org.f_cause_areas_ph": {
"en": "e.g. end-of-life, civil rights, scientific research, LGBTQI+, legal euthanasia, freedom of choice",
"it": "es. fine vita, diritti civili, ricerca scientifica, LGBTQI+, eutanasia legale, libertà di scelta"
},
"org.f_country": {
"en": "Country",
"it": "Paese"
},
"org.f_exclusion": {
"en": "Donor exclusion criteria",
"it": "Criteri di esclusione donatori"
},
"org.f_exclusion_ph": {
"en": "Sectors/people you don't want as donors. E.g. tobacco, weapons, gambling, mission conflicts. Claude will flag a red flag if the prospect falls here.",
"it": "Settori/persone che non volete come donor. Es: tabacco, armi, gioco d'azzardo, conflitti con la mission. Claude segnalerà red flag se il prospect ricade qui."
},
"org.f_founding_year": {
"en": "Founding year",
"it": "Anno di fondazione"
},
"org.f_fundraiser_email": {
"en": "Email",
"it": "Email"
},
"org.f_fundraiser_name": {
"en": "Name",
"it": "Nome"
},
"org.f_fundraiser_phone": {
"en": "Phone",
"it": "Telefono"
},
"org.f_giving_levels": {
"en": "Giving tiers (CSV)",
"it": "Tier di donazione (CSV)"
},
"org.f_hq_city": {
"en": "HQ city",
"it": "Città HQ"
},
"org.f_ideal_donor": {
"en": "Ideal donor profile",
"it": "Profilo donor ideale"
},
"org.f_ideal_donor_ph": {
"en": "E.g. liberal entrepreneurs, professionals, family offices sensitive to civil rights, secular foundations…",
"it": "Es. imprenditori liberali, professionisti, family office sensibili a diritti civili, fondazioni laiche…"
},
"org.f_kpi": {
"en": "Key results / KPIs",
"it": "Risultati chiave / KPI"
},
"org.f_kpi_ph": {
"en": "Measurable results from the last 2-3 years. Ammunition for the pitch.",
"it": "Risultati misurabili degli ultimi 2-3 anni. Munizioni per il pitch."
},
"org.f_legal_form": {
"en": "Legal form",
"it": "Forma giuridica"
},
"org.f_mission": {
"en": "Mission",
"it": "Mission"
},
"org.f_mission_ph": {
"en": "2-3 sentences: what you do and why the organization exists.",
"it": "2-3 frasi: cosa fate e perché esiste l'organizzazione."
},
"org.f_name": {
"en": "Organization name",
"it": "Nome organizzazione"
},
"org.f_name_ph": {
"en": "e.g. Luca Coscioni Association",
"it": "es. Associazione Luca Coscioni"
},
"org.f_notes_ph": {
"en": "E.g. annual events, longtime people, things to NEVER say, links to public documents, bylaws, social report…",
"it": "Es. eventi annuali, persone storiche, cose da NON dire mai, link a documenti pubblici, statuto, bilancio sociale…"
},
"org.f_partnerships": {
"en": "Historical partnerships / notable donors",
"it": "Partnership storiche / donor di rilievo"
},
"org.f_partnerships_ph": {
"en": "Companies, foundations, families that have supported you. Also helps Claude avoid suggesting names you already know.",
"it": "Aziende, fondazioni, famiglie che vi hanno sostenuto. Anche utile a Claude per evitare di proporre nomi già conosciuti."
},
"org.f_positioning": {
"en": "Distinctive positioning",
"it": "Posizionamento distintivo"
},
"org.f_positioning_ph": {
"en": "What sets you apart from other orgs doing similar work.",
"it": "Cosa vi distingue da altre org che fanno cose simili."
},
"org.f_programs": {
"en": "Active programs",
"it": "Programmi attivi"
},
"org.f_programs_ph": {
"en": "List active programs/projects. Claude will use the names to personalize next-best-actions.",
"it": "Elenca i programmi/progetti attivi. Claude userà i nomi per personalizzare le next-best-action."
},
"org.f_size": {
"en": "Size",
"it": "Dimensione"
},
"org.f_tone": {
"en": "Communication tone",
"it": "Tono comunicazione"
},
"org.f_tone_ph": {
"en": "e.g. institutional-warm, militant-direct, informative, intimate-confidential",
"it": "es. istituzionale-caloroso, militante-diretto, divulgativo, intimo confidenziale"
},
"org.f_value_prop": {
"en": "Value proposition for donors",
"it": "Value proposition per i donor"
},
"org.f_value_prop_ph": {
"en": "Why should a donor choose you? 2-3 sentence pitch.",
"it": "Perché un donor dovrebbe scegliere voi? 2-3 frasi pitch."
},
"org.f_vision": {
"en": "Vision",
"it": "Vision"
},
"org.f_vision_ph": {
"en": "The world you envision. 1-2 sentences.",
"it": "Il mondo che immaginate. 1-2 frasi."
},
"org.f_website": {
"en": "Website",
"it": "Sito web"
},
"org.footer_goto_research": {
"en": "Go to AI search",
"it": "Vai a ricerca AI"
},
"org.footer_note": {
"en": "This context will be included in all future AI searches.",
"it": "Il contesto sarà incluso in tutte le ricerche AI future."
},
"org.footer_save": {
"en": "Save context",
"it": "Salva contesto"
},
"org.identity": {
"en": "Identity",
"it": "Identità"
},
"org.identity_help": {
"en": "Who you are, where, how large you are.",
"it": "Chi siete, dove, quanto siete grandi."
},
"org.intro_post": {
"en": "into every AI search. The more detail you give Claude, the more relevant the profiles.",
"it": "in ogni ricerca AI. Più dettagli dai a Claude, più i profili saranno rilevanti."
},
"org.intro_pre": {
"en": "Everything you enter here is",
"it": "Tutto quello che inserisci qui viene"
},
"org.intro_strong": {
"en": "automatically injected",
"it": "iniettato automaticamente"
},
"org.opt_select": {
"en": "— Select —",
"it": "— Seleziona —"
},
"org.preview_help": {
"en": "Here's exactly what Claude reads before every AI search:",
"it": "Ecco esattamente cosa Claude legge prima di ogni ricerca AI:"
},
"org.preview_title": {
"en": "Preview of the briefing sent to Claude",
"it": "Anteprima briefing inviato a Claude"
},
"org.sec_causes": {
"en": "Causes, programs, results",
"it": "Cause, programmi, risultati"
},
"org.sec_causes_help": {
"en": "Claude calibrates each prospect's affinity score against these themes.",
"it": "Su questi temi Claude calibra l'affinity score di ogni prospect."
},
"org.sec_fundraiser": {
"en": "Lead fundraiser",
"it": "Fundraiser di riferimento"
},
"org.sec_fundraiser_help": {
"en": "To sign emails and generate personalized drafts.",
"it": "Per firmare email e generare drafts personalizzati."
},
"org.sec_mission": {
"en": "Mission & positioning",
"it": "Mission & posizionamento"
},
"org.sec_mission_help": {
"en": "The heart of who you are and why you exist. Claude will use this to align every profile.",
"it": "Il cuore di chi siete e perché esistete. Claude userà questo per allineare ogni profilo."
},
"org.sec_notes": {
"en": "Free notes",
"it": "Note libere"
},
"org.sec_notes_help": {
"en": "Anything that doesn't fit elsewhere. Claude will read this too.",
"it": "Tutto quello che non rientra altrove. Claude leggerà anche questo."
},
"org.sec_strategy": {
"en": "Fundraising strategy",
"it": "Strategia fundraising"
},
"org.sec_strategy_help": {
"en": "Ask tiers, ideal donor profile, exclusion criteria.",
"it": "Tier ask, profilo donor ideale, criteri esclusione."
},
"org.size_large": {
"en": "Large (>100)",
"it": "Large (>100)"
},
"org.size_medium": {
"en": "Medium (20–100)",
"it": "Medium (20–100)"
},
"org.size_micro": {
"en": "Micro (<5 people)",
"it": "Micro (<5 persone)"
},
"org.size_small": {
"en": "Small (5–20)",
"it": "Small (5–20)"
},
"org.status_configured": {
"en": "Configured",
"it": "Configurato"
},
"org.status_todo": {
"en": "To complete",
"it": "Da compilare"
},
"org.title": {
"en": "My organization",
"it": "La mia organizzazione"
},
"pdetail.activity_body_placeholder": {
"en": "Details, outcome, next steps…",
"it": "Dettagli, outcome, next steps…"
},
"pdetail.activity_empty": {
"en": "No activity",
"it": "Nessuna attività"
},
"pdetail.activity_title": {
"en": "Activity",
"it": "Attività"
},
"pdetail.activity_title_placeholder": {
"en": "Title (e.g. Call with assistant)",
"it": "Titolo (es. Call con assistente)"
},
"pdetail.activity_type_call": {
"en": "Call",
"it": "Telefonata"
},
"pdetail.activity_type_email": {
"en": "Email",
"it": "Email"
},
"pdetail.activity_type_meeting": {
"en": "Meeting",
"it": "Meeting"
},
"pdetail.activity_type_note": {
"en": "Note",
"it": "Nota"
},
"pdetail.activity_type_task": {
"en": "Task",
"it": "Task"
},
"pdetail.add_website_hint": {
"en": "Add the prospect's website to enable the search.",
"it": "Aggiungi il sito web del prospect per abilitare la ricerca."
},
"pdetail.affiliations_empty": {
"en": "No affiliations",
"it": "Nessuna affiliazione"
},
"pdetail.affiliations_title": {
"en": "Affiliations & board",
"it": "Affiliazioni & board"
},
"pdetail.ai_summary_title": {
"en": "AI Summary",
"it": "AI Summary"
},
"pdetail.back_to_top": {
"en": "↑ Back to top",
"it": "↑ Torna su"
},
"pdetail.breadcrumb_prospects": {
"en": "Prospects",
"it": "Prospect"
},
"pdetail.btn_add_activity": {
"en": "Add activity",
"it": "Aggiungi attività"
},
"pdetail.btn_ai_compose": {
"en": "AI Compose",
"it": "AI Compose"
},
"pdetail.btn_briefing": {
"en": "Briefing",
"it": "Briefing"
},
"pdetail.btn_cancel": {
"en": "Cancel",
"it": "Annulla"
},
"pdetail.btn_chat_ai": {
"en": "AI Chat",
"it": "Chat AI"
},
"pdetail.btn_deep_dive": {
"en": "Deep dive",
"it": "Deep dive"
},
"pdetail.btn_delete": {
"en": "Delete",
"it": "Elimina"
},
"pdetail.btn_edit": {
"en": "Edit",
"it": "Modifica"
},
"pdetail.btn_export_pdf": {
"en": "Export PDF",
"it": "Esporta PDF"
},
"pdetail.btn_export_pdf_title": {
"en": "Opens a printable preview · Save as PDF from the browser dialog",
"it": "Apre anteprima stampabile · Salva come PDF dal dialog del browser"
},
"pdetail.btn_find_dm_on": {
"en": "Find decision makers on",
"it": "Trova decision maker su"
},
"pdetail.btn_find_email": {
"en": "Find email",
"it": "Cerca email"
},
"pdetail.btn_force_refresh": {
"en": "Force refresh",
"it": "Force refresh"
},
"pdetail.btn_network": {
"en": "Network",
"it": "Network"
},
"pdetail.btn_new": {
"en": "New",
"it": "Nuova"
},
"pdetail.btn_recalculate": {
"en": "Recalculate",
"it": "Ricalcola"
},
"pdetail.btn_refetch_dm": {
"en": "Re-fetch decision makers",
"it": "Re-fetch decision maker"
},
"pdetail.btn_register_gift": {
"en": "Record",
"it": "Registra"
},
"pdetail.btn_save": {
"en": "Save changes",
"it": "Salva modifiche"
},
"pdetail.btn_search_news": {
"en": "Search news",
"it": "Cerca news"
},
"pdetail.btn_sequence": {
"en": "Sequence",
"it": "Sequence"
},
"pdetail.btn_start_research": {
"en": "Start AI research",
"it": "Avvia ricerca AI"
},
"pdetail.btn_suggest_ask": {
"en": "Suggest ask",
"it": "Suggerisci ask"
},
"pdetail.btn_update_ai_insights": {
"en": "Refresh AI insights",
"it": "Aggiorna insights AI"
},
"pdetail.btn_update_research": {
"en": "Refresh research",
"it": "Aggiorna ricerca"
},
"pdetail.btn_use_in_pipeline": {
"en": "Use in pipeline",
"it": "Usa nella pipeline"
},
"pdetail.btn_verify_content": {
"en": "Verify in content (AI)",
"it": "Verifica nel contenuto (AI)"
},
"pdetail.btn_verify_links": {
"en": "Verify links",
"it": "Verifica link"
},
"pdetail.busy_calculating": {
"en": "Calculating…",
"it": "Calcolo…"
},
"pdetail.busy_deep_diving": {
"en": "Diving deeper…",
"it": "Approfondisco…"
},
"pdetail.busy_reading_sources": {
"en": "Reading sources…",
"it": "Leggo le fonti…"
},
"pdetail.busy_searching": {
"en": "Searching…",
"it": "Cerco…"
},
"pdetail.busy_searching_news": {
"en": "Searching news…",
"it": "Cerco news…"
},
"pdetail.busy_updating": {
"en": "Updating…",
"it": "Aggiorno…"
},
"pdetail.busy_verifying": {
"en": "Verifying…",
"it": "Verifico…"
},
"pdetail.confirm_delete_gift": {
"en": "Delete this gift?",
"it": "Eliminare questa donazione?"
},
"pdetail.confirm_delete_prospect": {
"en": "Permanently delete",
"it": "Eliminare definitivamente"
},
"pdetail.confirm_force_refresh": {
"en": "Forcing consumes 1 Hunter credit. Proceed?",
"it": "Forzare consuma 1 credito Hunter. Procedere?"
},
"pdetail.confirm_refetch": {
"en": "Re-fetch may consume 1 Hunter credit. Proceed?",
"it": "Il re-fetch puo consumare 1 credito Hunter. Procedere?"
},
"pdetail.connections_empty": {
"en": "No connections",
"it": "Nessuna connessione"
},
"pdetail.connections_title": {
"en": "Connections & network",
"it": "Connessioni & network"
},
"pdetail.contacts": {
"en": "contacts",
"it": "contatti"
},
"pdetail.created": {
"en": "Created",
"it": "Creato"
},
"pdetail.current_ask_in_pipeline": {
"en": "Current ask in pipeline:",
"it": "Ask attuale in pipeline:"
},
"pdetail.decision_makers_title": {
"en": "Decision makers & email",
"it": "Decision maker & email"
},
"pdetail.deep_dive_affiliations_title": {
"en": "Targeted AI research on affiliations",
"it": "Ricerca AI mirata su affiliazioni"
},
"pdetail.deep_dive_giving_title": {
"en": "Targeted AI research on philanthropic history",
"it": "Ricerca AI mirata sullo storico filantropico"
},
"pdetail.deep_dive_network_title": {
"en": "Targeted AI research on the network",
"it": "Ricerca AI mirata sul network"
},
"pdetail.deep_dive_wealth_title": {
"en": "Targeted AI research on wealth",
"it": "Ricerca AI mirata su wealth"
},
"pdetail.domain_label": {
"en": "Domain",
"it": "Dominio"
},
"pdetail.draft_sent": {
"en": "sent",
"it": "inviata"
},
"pdetail.drafts_title": {
"en": "Email drafts",
"it": "Bozze email"
},
"pdetail.edit_profile_subtitle": {
"en": "Manually update the CRM fields",
"it": "Aggiorna manualmente i campi del CRM"
},
"pdetail.edit_profile_title": {
"en": "Edit profile",
"it": "Modifica profilo"
},
"pdetail.empty_profile_desc": {
"en": "Start the AI research: Claude searches public sources and fills in capacity, affinity, board roles, giving, network and sources.",
"it": "Avvia la ricerca AI: Claude cerca su fonti pubbliche e compila capacità, affinità, board, donazioni, network e fonti."
},
"pdetail.empty_profile_title": {
"en": "Profile still empty",
"it": "Profilo ancora vuoto"
},
"pdetail.error": {
"en": "error",
"it": "errore"
},
"pdetail.estimated_net_worth": {
"en": "Estimated net worth",
"it": "Net worth stimato"
},
"pdetail.field_ask_amount": {
"en": "Ask amount (EUR)",
"it": "Ask amount (EUR)"
},
"pdetail.field_company": {
"en": "Company",
"it": "Azienda"
},
"pdetail.field_country": {
"en": "Country",
"it": "Paese"
},
"pdetail.field_email": {
"en": "Email",
"it": "Email"
},
"pdetail.field_estimated_net_worth": {
"en": "Estimated net worth",
"it": "Net worth stimato"
},
"pdetail.field_full_name": {
"en": "Full name",
"it": "Nome"
},
"pdetail.field_headline": {
"en": "Headline",
"it": "Headline"
},
"pdetail.field_headline_placeholder": {
"en": "e.g. CEO Acme · ex Goldman · Telethon board",
"it": "es. CEO Acme · ex Goldman · board Telethon"
},
"pdetail.field_internal_notes": {
"en": "Internal notes",
"it": "Note interne"
},
"pdetail.field_linkedin_url": {
"en": "LinkedIn URL",
"it": "LinkedIn URL"
},
"pdetail.field_location": {
"en": "Location",
"it": "Location"
},
"pdetail.field_location_placeholder": {
"en": "Milan, Italy",
"it": "Milano, Italia"
},
"pdetail.field_net_worth_placeholder": {
"en": "e.g. 5-10M EUR (estimate)",
"it": "es. 5-10M EUR (stima)"
},
"pdetail.field_notes_placeholder": {
"en": "Context, past conversations, preferences, next steps…",
"it": "Contesto, conversazioni intercorse, preferenze, next steps…"
},
"pdetail.field_phone": {
"en": "Phone",
"it": "Telefono"
},
"pdetail.field_priority": {
"en": "Priority",
"it": "Priorità"
},
"pdetail.field_role": {
"en": "Role",
"it": "Ruolo"
},
"pdetail.field_sectors": {
"en": "Sectors (comma-separated)",
"it": "Settori (separati da virgola)"
},
"pdetail.field_stage": {
"en": "Stage",
"it": "Stage"
},
"pdetail.field_twitter": {
"en": "Twitter handle",
"it": "Twitter handle"
},
"pdetail.field_type": {
"en": "Type",
"it": "Tipo"
},
"pdetail.field_website": {
"en": "Website",
"it": "Sito web"
},
"pdetail.find_person_email_title": {
"en": "Find a specific person's email",
"it": "Trova email di una persona specifica"
},
"pdetail.find_person_hint": {
"en": "Hunter looks up the email by matching first + last name to the domain. It consumes 1 credit even if nothing is found.",
"it": "Hunter cerca l'email associando nome+cognome al dominio. Consuma 1 credito anche se non trova nulla."
},
"pdetail.first_name_label": {
"en": "First name",
"it": "Nome"
},
"pdetail.generated_by_claude": {
"en": "Generated by Claude",
"it": "Generato da Claude"
},
"pdetail.gift_amount_label": {
"en": "Amount €",
"it": "Importo €"
},
"pdetail.gift_campaign_label": {
"en": "Campaign",
"it": "Campagna"
},
"pdetail.gift_campaign_placeholder": {
"en": "e.g. 5x1000",
"it": "es. 5x1000"
},
"pdetail.gift_date_label": {
"en": "Date",
"it": "Data"
},
"pdetail.gift_kind_label": {
"en": "Type",
"it": "Tipo"
},
"pdetail.gift_status_label": {
"en": "Status",
"it": "Stato"
},
"pdetail.gifts_empty": {
"en": "No gifts recorded. When you receive a gift (or a pledge), record it here: it feeds the forecast, total raised and stewardship cycle.",
"it": "Nessuna donazione registrata. Quando incassi (o ricevi una promessa), registrala qui: alimenta forecast, raccolto e ciclo di ringraziamento."
},
"pdetail.gifts_raised": {
"en": "Raised (received)",
"it": "Raccolto (incassato)"
},
"pdetail.gifts_to_us_title": {
"en": "Gifts to us",
"it": "Donazioni a noi"
},
"pdetail.giving_empty": {
"en": "No known giving",
"it": "Nessuna donazione nota"
},
"pdetail.giving_history_title": {
"en": "Giving history",
"it": "Storico donazioni"
},
"pdetail.ground_sources_title": {
"en": "The AI opens the sources and checks whether they actually SUPPORT the profile data",
"it": "L'AI apre le fonti e verifica se SUPPORTANO davvero i dati del profilo"
},
"pdetail.in_crm": {
"en": "in CRM",
"it": "nel CRM"
},
"pdetail.in_pipeline": {
"en": "In pipeline",
"it": "In pipeline"
},
"pdetail.internal_notes_title": {
"en": "Internal notes",
"it": "Note interne"
},
"pdetail.investigating_detail": {
"en": "Web search, source fetching, profile synthesis. The page will refresh automatically.",
"it": "Web search, fetch fonti, sintesi profilo. La pagina si aggiornerà automaticamente."
},
"pdetail.investigating_prefix": {
"en": "Claude is investigating",
"it": "Claude sta investigando"
},
"pdetail.job_done": {
"en": "completed",
"it": "completata"
},
"pdetail.job_error": {
"en": "error",
"it": "errore"
},
"pdetail.job_pending": {
"en": "queued",
"it": "in coda"
},
"pdetail.job_running": {
"en": "running",
"it": "in corso"
},
"pdetail.last_name_label": {
"en": "Last name",
"it": "Cognome"
},
"pdetail.mark_thanked_title": {
"en": "Mark as thanked",
"it": "Segna come ringraziato"
},
"pdetail.news_empty": {
"en": "No news yet. Click \"Search news\" to look for recent mentions.",
"it": "Nessuna news ancora. Clicca \"Cerca news\" per cercare menzioni recenti."
},
"pdetail.news_high_relevance": {
"en": "high relevance",
"it": "alta rilevanza"
},
"pdetail.news_opportunity_headline": {
"en": "Favorable moment for the ask.",
"it": "Momento favorevole per l'ask."
},
"pdetail.news_positive_signals": {
"en": "positive signal(s) from recent news.",
"it": "segnale/i positivo/i dalle news recenti."
},
"pdetail.news_signal_opportunity": {
"en": "opportunity",
"it": "opportunità"
},
"pdetail.news_signal_risk": {
"en": "caution",
"it": "attenzione"
},
"pdetail.news_title": {
"en": "News & mentions",
"it": "News & menzioni"
},
"pdetail.news_why_matters": {
"en": "Why it matters:",
"it": "Perché conta:"
},
"pdetail.next_best_action": {
"en": "Next best action",
"it": "Next best action"
},
"pdetail.no_decision_makers": {
"en": "No decision makers yet",
"it": "Nessun decision maker ancora"
},
"pdetail.one_credit": {
"en": "1 credit",
"it": "1 credito"
},
"pdetail.priority_high": {
"en": "High",
"it": "Alta"
},
"pdetail.priority_low": {
"en": "Low",
"it": "Bassa"
},
"pdetail.priority_medium": {
"en": "Medium",
"it": "Media"
},
"pdetail.priority_prefix": {
"en": "Priority",
"it": "Priorità"
},
"pdetail.quick_summary_title": {
"en": "Quick summary",
"it": "Sintesi rapida"
},
"pdetail.range_label": {
"en": "Range:",
"it": "Range:"
},
"pdetail.records": {
"en": "records",
"it": "record"
},
"pdetail.red_flags": {
"en": "Red flags",
"it": "Red flags"
},
"pdetail.red_flags_warning": {
"en": "Caution (red flags):",
"it": "Attenzione (red flags):"
},
"pdetail.remove": {
"en": "Remove",
"it": "Rimuovi"
},
"pdetail.research_error": {
"en": "Research error:",
"it": "Errore ricerca:"
},
"pdetail.research_running": {
"en": "Research running",
"it": "Ricerca in corso"
},
"pdetail.score_affinity": {
"en": "Affinity",
"it": "Affinità"
},
"pdetail.score_ask": {
"en": "Ask",
"it": "Ask"
},
"pdetail.score_capacity": {
"en": "Capacity",
"it": "Capacità"
},
"pdetail.score_propensity": {
"en": "Propensity",
"it": "Propensione"
},
"pdetail.search_clevel_hint": {
"en": "only C-level / executives (1 Hunter credit, 30-day cache).",
"it": "solo C-level / executive (1 credito Hunter, cache 30 giorni)."
},
"pdetail.search_on": {
"en": "Search on",
"it": "Cerca su"
},
"pdetail.section_contacts": {
"en": "Contacts",
"it": "Contatti"
},
"pdetail.section_geography": {
"en": "Geography",
"it": "Geografia"
},
"pdetail.section_identity": {
"en": "Identity",
"it": "Identità"
},
"pdetail.section_notes": {
"en": "Notes",
"it": "Note"
},
"pdetail.section_pipeline": {
"en": "Pipeline & rating",
"it": "Pipeline & valutazione"
},
"pdetail.sectors": {
"en": "Sectors",
"it": "Settori"
},
"pdetail.see_network": {
"en": "View network →",
"it": "Vedi network →"
},
"pdetail.sentiment_negative": {
"en": "negative",
"it": "negativo"
},
"pdetail.sentiment_neutral": {
"en": "neutral",
"it": "neutro"
},
"pdetail.sentiment_positive": {
"en": "positive",
"it": "positivo"
},
"pdetail.seq_sent": {
"en": "sent",
"it": "inviate"
},
"pdetail.seq_steps": {
"en": "steps",
"it": "step"
},
"pdetail.sequences_empty": {
"en": "No sequences yet.",
"it": "Nessuna sequence ancora."
},
"pdetail.sequences_empty_cta": {
"en": "+ Generate your first sequence",
"it": "+ Genera la prima sequence"
},
"pdetail.sequences_title": {
"en": "Email sequences",
"it": "Sequence email"
},
"pdetail.source": {
"en": "Source",
"it": "Source"
},
"pdetail.sources_broken": {
"en": "broken",
"it": "rotte"
},
"pdetail.sources_confirm": {
"en": "confirm",
"it": "confermano"
},
"pdetail.sources_contradict": {
"en": "contradict",
"it": "contraddicono"
},
"pdetail.sources_empty": {
"en": "No sources",
"it": "Nessuna fonte"
},
"pdetail.sources_grounded_ko_title": {
"en": "Sources that contradict",
"it": "Fonti che contraddicono"
},
"pdetail.sources_grounded_ok_title": {
"en": "Sources that confirm the data in their content",
"it": "Fonti che confermano i dati nel contenuto"
},
"pdetail.sources_restricted": {
"en": "restricted access",
"it": "accesso limitato"
},
"pdetail.sources_title": {
"en": "AI research sources",
"it": "Fonti ricerca AI"
},
"pdetail.sources_unchecked": {
"en": "to verify",
"it": "da verificare"
},
"pdetail.sources_verified": {
"en": "verified",
"it": "verificate"
},
"pdetail.src_confirms_data": {
"en": "Confirms the data.",
"it": "Conferma il dato."
},
"pdetail.src_contradicts": {
"en": "Contradicts.",
"it": "Contraddice."
},
"pdetail.src_not_found": {
"en": "Data not found in the content.",
"it": "Dato non trovato nel contenuto."
},
"pdetail.src_restricted_title": {
"en": "Restricted access (the page exists)",
"it": "Accesso limitato (la pagina esiste)"
},
"pdetail.src_unchecked_title": {
"en": "Not verified",
"it": "Non verificata"
},
"pdetail.src_unreachable_title": {
"en": "Unreachable",
"it": "Non raggiungibile"
},
"pdetail.src_verified_title": {
"en": "Verified",
"it": "Verificata"
},
"pdetail.stage_prefix": {
"en": "Stage:",
"it": "Stage:"
},
"pdetail.suggested_ask_empty": {
"en": "AI suggests an amount to ask for — with a range and rationale — based on capacity, affinity, giving history and your typical gift tiers.",
"it": "L'AI propone un importo da chiedere — con range e motivazione — basato su capacità, affinità, storico e i tuoi tier tipici."
},
"pdetail.suggested_ask_title": {
"en": "Suggested ask",
"it": "Ask consigliato"
},
"pdetail.suggested_target": {
"en": "Suggested target",
"it": "Target consigliato"
},
"pdetail.tags_existing_option": {
"en": "— Existing —",
"it": "— Esistenti —"
},
"pdetail.tags_new_placeholder": {
"en": "or new tag",
"it": "oppure nuovo tag"
},
"pdetail.tags_title": {
"en": "Tags",
"it": "Tag"
},
"pdetail.task_placeholder": {
"en": "Add task…",
"it": "Aggiungi task…"
},
"pdetail.tasks_empty": {
"en": "No tasks",
"it": "Nessun task"
},
"pdetail.tasks_open": {
"en": "open",
"it": "aperti"
},
"pdetail.tasks_title": {
"en": "Tasks",
"it": "Tasks"
},
"pdetail.th_amount": {
"en": "Amount",
"it": "Importo"
},
"pdetail.th_campaign": {
"en": "Campaign",
"it": "Campagna"
},
"pdetail.th_category": {
"en": "Category",
"it": "Categoria"
},
"pdetail.th_cause": {
"en": "Cause",
"it": "Causa"
},
"pdetail.th_conf": {
"en": "Conf.",
"it": "Conf."
},
"pdetail.th_context": {
"en": "Context",
"it": "Contesto"
},
"pdetail.th_date": {
"en": "Date",
"it": "Data"
},
"pdetail.th_detail": {
"en": "Detail",
"it": "Dettaglio"
},
"pdetail.th_email": {
"en": "Email",
"it": "Email"
},
"pdetail.th_indicator": {
"en": "Indicator",
"it": "Indicatore"
},
"pdetail.th_kind": {
"en": "Type",
"it": "Tipo"
},
"pdetail.th_name": {
"en": "Name",
"it": "Nome"
},
"pdetail.th_organization": {
"en": "Organization",
"it": "Organizzazione"
},
"pdetail.th_period": {
"en": "Period",
"it": "Periodo"
},
"pdetail.th_relationship": {
"en": "Relationship",
"it": "Relazione"
},
"pdetail.th_role": {
"en": "Role",
"it": "Ruolo"
},
"pdetail.th_source": {
"en": "Source",
"it": "Fonte"
},
"pdetail.th_status": {
"en": "Status",
"it": "Stato"
},
"pdetail.th_strength": {
"en": "Strength",
"it": "Forza"
},
"pdetail.th_thanked": {
"en": "Thanked",
"it": "Ringraziato"
},
"pdetail.th_value": {
"en": "Value",
"it": "Valore"
},
"pdetail.th_year": {
"en": "Year",
"it": "Anno"
},
"pdetail.thanked_at_title": {
"en": "Thanked on",
"it": "Ringraziato"
},
"pdetail.thanked_click_undo": {
"en": "click to undo",
"it": "clic per annullare"
},
"pdetail.thanked_todo": {
"en": "to do",
"it": "da fare"
},
"pdetail.thanked_yes": {
"en": "yes",
"it": "sì"
},
"pdetail.updated": {
"en": "Updated",
"it": "Aggiornato"
},
"pdetail.use_in_pipeline_title": {
"en": "Set this amount as the prospect's ask: it will feed into the pipeline forecast",
"it": "Imposta questo importo come ask del prospect: entrerà nel forecast della pipeline"
},
"pdetail.verify_links_title": {
"en": "Check that the URLs respond",
"it": "Controlla che gli URL rispondano"
},
"pdetail.wealth_empty": {
"en": "No wealth indicators. Run Refresh research.",
"it": "Nessun wealth indicator. Esegui Aggiorna ricerca."
},
"pdetail.wealth_title": {
"en": "Wealth indicators",
"it": "Wealth indicators"
},
"pdf.affiliations_board": {
"en": "Affiliations & board",
"it": "Affiliazioni & board"
},
"pdf.ai_summary": {
"en": "AI summary",
"it": "Sintesi AI"
},
"pdf.close": {
"en": "Close",
"it": "Chiudi"
},
"pdf.company": {
"en": "Company",
"it": "Azienda"
},
"pdf.connections_network": {
"en": "Connections & network",
"it": "Connessioni & network"
},
"pdf.decision_makers_email": {
"en": "Decision makers & email",
"it": "Decision maker & email"
},
"pdf.footer_disclaimer": {
"en": "Information is drawn from public sources processed via AI. Verify before acting on the contact.",
"it": "Le informazioni provengono da fonti pubbliche elaborate via AI. Verificare prima di azionare il contatto."
},
"pdf.footer_generated": {
"en": "Document generated automatically by Forager — Prospect Research CRM",
"it": "Documento generato automaticamente da Forager — Prospect Research CRM"
},
"pdf.generated_by_claude": {
"en": "generated by Claude",
"it": "generata da Claude"
},
"pdf.giving_history": {
"en": "Giving history",
"it": "Storico donazioni"
},
"pdf.identity_contacts": {
"en": "Identity & contacts",
"it": "Identità & contatti"
},
"pdf.in_crm": {
"en": "in CRM",
"it": "nel CRM"
},
"pdf.internal_notes": {
"en": "Internal notes",
"it": "Note interne"
},
"pdf.items": {
"en": "items",
"it": "item"
},
"pdf.kv_country": {
"en": "Country",
"it": "Paese"
},
"pdf.kv_email": {
"en": "Email",
"it": "Email"
},
"pdf.kv_linkedin": {
"en": "LinkedIn",
"it": "LinkedIn"
},
"pdf.kv_net_worth": {
"en": "Estimated net worth",
"it": "Patrimonio stimato"
},
"pdf.kv_phone": {
"en": "Phone",
"it": "Telefono"
},
"pdf.kv_sectors": {
"en": "Sectors",
"it": "Settori"
},
"pdf.kv_source": {
"en": "Record source",
"it": "Origine record"
},
"pdf.kv_twitter": {
"en": "Twitter",
"it": "Twitter"
},
"pdf.kv_website": {
"en": "Website",
"it": "Sito web"
},
"pdf.location": {
"en": "Location",
"it": "Luogo"
},
"pdf.news_mentions": {
"en": "Recent news & mentions",
"it": "News & menzioni recenti"
},
"pdf.next_best_action": {
"en": "Next best action",
"it": "Next best action"
},
"pdf.page_abbr": {
"en": "Page",
"it": "Pag."
},
"pdf.page_generated": {
"en": "generated",
"it": "generato"
},
"pdf.preview_hint": {
"en": "Save as PDF via \"Print\"",
"it": "Salva come PDF tramite \"Stampa\""
},
"pdf.preview_title": {
"en": "PDF preview",
"it": "Anteprima PDF"
},
"pdf.print_save": {
"en": "Print / Save PDF",
"it": "Stampa / Salva PDF"
},
"pdf.priority": {
"en": "Priority",
"it": "Priorità"
},
"pdf.records": {
"en": "records",
"it": "record"
},
"pdf.red_flags": {
"en": "Red flags",
"it": "Red flags"
},
"pdf.relevance": {
"en": "relevance",
"it": "rilevanza"
},
"pdf.role": {
"en": "Role",
"it": "Ruolo"
},
"pdf.sources": {
"en": "sources",
"it": "fonti"
},
"pdf.sources_consulted": {
"en": "Sources consulted",
"it": "Fonti consultate"
},
"pdf.suggested_ask": {
"en": "Suggested ask",
"it": "Ask suggerito"
},
"pdf.th_amount_eur": {
"en": "Amount €",
"it": "Importo €"
},
"pdf.th_category": {
"en": "Category",
"it": "Categoria"
},
"pdf.th_cause": {
"en": "Cause",
"it": "Causa"
},
"pdf.th_conf": {
"en": "Conf.",
"it": "Conf."
},
"pdf.th_context": {
"en": "Context",
"it": "Contesto"
},
"pdf.th_detail": {
"en": "Detail",
"it": "Dettaglio"
},
"pdf.th_email": {
"en": "Email",
"it": "Email"
},
"pdf.th_indicator": {
"en": "Indicator",
"it": "Indicatore"
},
"pdf.th_name": {
"en": "Name",
"it": "Nome"
},
"pdf.th_organization": {
"en": "Organization",
"it": "Organizzazione"
},
"pdf.th_period": {
"en": "Period",
"it": "Periodo"
},
"pdf.th_relationship": {
"en": "Relationship",
"it": "Relazione"
},
"pdf.th_role": {
"en": "Role",
"it": "Ruolo"
},
"pdf.th_strength": {
"en": "Strength",
"it": "Forza"
},
"pdf.th_type": {
"en": "Type",
"it": "Tipo"
},
"pdf.th_value_eur": {
"en": "Value €",
"it": "Valore €"
},
"pdf.th_year": {
"en": "Year",
"it": "Anno"
},
"pdf.wealth_indicators": {
"en": "Wealth indicators",
"it": "Wealth indicators"
},
"plist.aggiungi_manualmente": {
"en": "Add manually",
"it": "Aggiungi manualmente"
},
"plist.alta": {
"en": "High",
"it": "Alta"
},
"plist.applica_priorita": {
"en": "Apply priority",
"it": "Applica priorità"
},
"plist.applica_stage": {
"en": "Apply stage",
"it": "Applica stage"
},
"plist.avvia_ricerca": {
"en": "Start research",
"it": "Avvia ricerca"
},
"plist.bassa": {
"en": "Low",
"it": "Bassa"
},
"plist.cambia_stage": {
"en": "Change stage…",
"it": "Cambia stage…"
},
"plist.cerca_placeholder": {
"en": "Search by name, company, role, sector…",
"it": "Cerca per nome, azienda, ruolo, settore…"
},
"plist.col_ask": {
"en": "Ask",
"it": "Ask"
},
"plist.col_capacity": {
"en": "Capacity",
"it": "Capacity"
},
"plist.col_location": {
"en": "Location",
"it": "Location"
},
"plist.col_priorita": {
"en": "Priority",
"it": "Priorità"
},
"plist.col_priorita_ai": {
"en": "AI priority",
"it": "Priorità AI"
},
"plist.col_priorita_ai_tip": {
"en": "Combined score: capacity + propensity + affinity",
"it": "Punteggio combinato: capacità + propensione + affinità"
},
"plist.col_propensity": {
"en": "Propensity",
"it": "Propensity"
},
"plist.col_prospect": {
"en": "Prospect",
"it": "Prospect"
},
"plist.col_stage": {
"en": "Stage",
"it": "Stage"
},
"plist.col_tipo": {
"en": "Type",
"it": "Tipo"
},
"plist.confirm_elimina": {
"en": "Permanently delete the selected items?",
"it": "Eliminare definitivamente i selezionati?"
},
"plist.confirm_ricerca_bulk": {
"en": "Run AI research on all selected? This uses N Claude calls.",
"it": "Avviare ricerca AI su tutti i selezionati? Consuma N chiamate Claude."
},
"plist.deseleziona": {
"en": "Deselect",
"it": "Deseleziona"
},
"plist.di": {
"en": "of",
"it": "di"
},
"plist.elimina": {
"en": "Delete",
"it": "Elimina"
},
"plist.empty_desc": {
"en": "Start with AI research, import a CSV, or add one manually.",
"it": "Inizia con una ricerca AI, importa CSV, o aggiungi manualmente."
},
"plist.empty_title": {
"en": "No prospects found",
"it": "Nessun prospect trovato"
},
"plist.export": {
"en": "Export",
"it": "Export"
},
"plist.filtra": {
"en": "Filter",
"it": "Filtra"
},
"plist.importa_csv": {
"en": "Import CSV",
"it": "Importa CSV"
},
"plist.media": {
"en": "Medium",
"it": "Media"
},
"plist.nuovo": {
"en": "New",
"it": "Nuovo"
},
"plist.pagina": {
"en": "Page",
"it": "Pagina"
},
"plist.pipeline": {
"en": "Pipeline",
"it": "Pipeline"
},
"plist.precedente": {
"en": "Previous",
"it": "Precedente"
},
"plist.priorita_placeholder": {
"en": "Priority…",
"it": "Priorità…"
},
"plist.ricerca_bulk": {
"en": "Bulk research",
"it": "Ricerca bulk"
},
"plist.risultati": {
"en": "results",
"it": "risultati"
},
"plist.selezionati": {
"en": "selected",
"it": "selezionati"
},
"plist.sort_ask": {
"en": "Ask amount",
"it": "Ask amount"
},
"plist.sort_nome": {
"en": "Name A-Z",
"it": "Nome A-Z"
},
"plist.sort_priorita": {
"en": "Priority (recommended)",
"it": "Priorità (consigliato)"
},
"plist.sort_propensity": {
"en": "Top propensity",
"it": "Top propensity"
},
"plist.sort_recenti": {
"en": "Most recent",
"it": "Più recenti"
},
"plist.successiva": {
"en": "Next",
"it": "Successiva"
},
"plist.title": {
"en": "Prospects",
"it": "Prospect"
},
"plist.totali_pipeline_aperta": {
"en": "total · open pipeline",
"it": "totali · pipeline aperta"
},
"plist.tutti_gli_stage": {
"en": "All stages",
"it": "Tutti gli stage"
},
"plist.tutti_i_tipi": {
"en": "All types",
"it": "Tutti i tipi"
},
"pnew.annulla": {
"en": "Cancel",
"it": "Annulla"
},
"pnew.crea_comunque": {
"en": "Create anyway",
"it": "Crea comunque"
},
"pnew.crea_prospect": {
"en": "Create prospect",
"it": "Crea prospect"
},
"pnew.dup_apri_esistente": {
"en": "Open existing",
"it": "Apri esistente"
},
"pnew.dup_desc": {
"en": "This looks like a duplicate (same name/email/domain). Open the existing record to avoid duplicates, or create it anyway if it is a different person/organization.",
"it": "Sembra un duplicato (stesso nome/email/dominio). Apri l'esistente per evitare doppioni, oppure crea comunque se è un'altra persona/ente."
},
"pnew.dup_forse_esiste": {
"en": "May already exist:",
"it": "Forse esiste già:"
},
"pnew.dup_oppure": {
"en": "↓ or use \"Create anyway\" below",
"it": "↓ oppure usa \"Crea comunque\" qui sotto"
},
"pnew.lbl_azienda": {
"en": "Company",
"it": "Azienda"
},
"pnew.lbl_email": {
"en": "Email",
"it": "Email"
},
"pnew.lbl_linkedin": {
"en": "LinkedIn",
"it": "LinkedIn"
},
"pnew.lbl_location": {
"en": "Location",
"it": "Location"
},
"pnew.lbl_nome_azienda": {
"en": "Name / Company",
"it": "Nome / Azienda"
},
"pnew.lbl_note": {
"en": "Notes / context",
"it": "Note / contesto"
},
"pnew.lbl_paese": {
"en": "Country",
"it": "Paese"
},
"pnew.lbl_priorita": {
"en": "Priority",
"it": "Priorità"
},
"pnew.lbl_ruolo": {
"en": "Role",
"it": "Ruolo"
},
"pnew.lbl_settori": {
"en": "Sectors",
"it": "Settori"
},
"pnew.lbl_sito_web": {
"en": "Website",
"it": "Sito web"
},
"pnew.lbl_stage_iniziale": {
"en": "Initial stage",
"it": "Stage iniziale"
},
"pnew.lbl_tipo": {
"en": "Type",
"it": "Tipo"
},
"pnew.nuovo": {
"en": "New",
"it": "Nuovo"
},
"pnew.ph_azienda": {
"en": "e.g. Tod's SpA",
"it": "es. Tod's SpA"
},
"pnew.ph_email": {
"en": "optional",
"it": "opzionale"
},
"pnew.ph_location": {
"en": "e.g. Milan, Italy",
"it": "es. Milano, Italia"
},
"pnew.ph_nome": {
"en": "e.g. Diego Della Valle",
"it": "es. Diego Della Valle"
},
"pnew.ph_note": {
"en": "Context, why you're adding them, causes of interest, prior contact…",
"it": "Contesto, perché lo stai inserendo, cause di interesse, contatti già intercorsi…"
},
"pnew.ph_paese": {
"en": "e.g. Italy",
"it": "es. Italia"
},
"pnew.ph_ruolo": {
"en": "e.g. Chairman",
"it": "es. Presidente"
},
"pnew.ph_settori": {
"en": "e.g. luxury, retail, fashion",
"it": "es. luxury, retail, moda"
},
"pnew.prio_alta": {
"en": "High",
"it": "Alta"
},
"pnew.prio_bassa": {
"en": "Low",
"it": "Bassa"
},
"pnew.prio_media": {
"en": "Medium",
"it": "Media"
},
"pnew.prospect": {
"en": "Prospects",
"it": "Prospect"
},
"pnew.run_research_desc": {
"en": "Claude scans the web and populates wealth indicators, board memberships, giving history and photo.",
"it": "Claude analizza il web, popola wealth indicators, board, giving history e foto."
},
"pnew.run_research_title": {
"en": "Start AI research immediately",
"it": "Avvia ricerca AI immediatamente"
},
"pnew.subtitle": {
"en": "Enter a name and context. Optionally start AI research right away.",
"it": "Inserisci nome e contesto. Opzionalmente avvia subito la ricerca AI."
},
"pnew.tipo_azienda": {
"en": "(company)",
"it": "(azienda)"
},
"pnew.tipo_ente": {
"en": "(grantmaker)",
"it": "(ente erogatore)"
},
"pnew.tipo_persona": {
"en": "(person)",
"it": "(persona)"
},
"pnew.title": {
"en": "New prospect",
"it": "Nuovo prospect"
},
"research.briefing_active": {
"en": "Active briefing:",
"it": "Briefing attivo:"
},
"research.btn_run": {
"en": "Start AI research",
"it": "Avvia ricerca AI"
},
"research.btn_run_anyway": {
"en": "Run anyway",
"it": "Avvia comunque"
},
"research.dup_warning": {
"en": "already seems to be in the CRM. Open it to avoid duplicating the research, or run it anyway below.",
"it": "sembra già nel CRM. Aprilo per non duplicare la ricerca, oppure avvia comunque qui sotto."
},
"research.edit": {
"en": "Edit",
"it": "Modifica"
},
"research.ethics": {
"en": "Ethics",
"it": "Etica"
},
"research.ethics_body": {
"en": "Public sources only. GDPR compliant. Capacity estimates are indicative — always verify before the ask.",
"it": "Solo fonti pubbliche. Rispetto GDPR. Le stime di capacity sono indicative — verifica sempre prima dell'ask."
},
"research.field_context": {
"en": "Context",
"it": "Contesto"
},
"research.field_context_ph": {
"en": "Helps disambiguate: company, sector, domain…",
"it": "Aiuta a disambiguare: azienda, settore, dominio…"
},
"research.field_country": {
"en": "Country",
"it": "Paese"
},
"research.field_country_ph": {
"en": "Italy",
"it": "Italia"
},
"research.field_focus": {
"en": "Research focus",
"it": "Focus della ricerca"
},
"research.field_focus_ph": {
"en": "What do you want to find out? E.g. giving capacity, board memberships, past CSR, affinity to specific causes…",
"it": "Cosa ti interessa scoprire? Es: capacità di donazione, board memberships, CSR pregressi, predisposizione a cause specifiche…"
},
"research.field_name": {
"en": "Name / Company",
"it": "Nome / Azienda"
},
"research.field_name_ph": {
"en": "e.g. Brunello Cucinelli · Generali · Fondazione Cariplo",
"it": "es. Brunello Cucinelli · Generali · Fondazione Cariplo"
},
"research.field_type": {
"en": "Type",
"it": "Tipo"
},
"research.how_it_works": {
"en": "How it works",
"it": "Come funziona"
},
"research.new_search": {
"en": "New AI research",
"it": "Nuova ricerca AI"
},
"research.new_search_hint": {
"en": "Enter a name or a company. Average time: 1–3 minutes.",
"it": "Inserisci un nome o un'azienda. Tempo medio: 1–3 minuti."
},
"research.no_briefing_body": {
"en": "Set up mission, causes and ask tiers to calibrate research to your context.",
"it": "Configura mission, cause e tier ask per calibrare le ricerche sul tuo contesto."
},
"research.no_briefing_title": {
"en": "No organization briefing.",
"it": "Nessun briefing organizzazione."
},
"research.no_jobs": {
"en": "No jobs yet",
"it": "Nessun job ancora"
},
"research.open": {
"en": "Open",
"it": "Apri"
},
"research.recent_jobs": {
"en": "Recent jobs",
"it": "Job recenti"
},
"research.step_1": {
"en": "Enter name and context.",
"it": "Inserisci nome e contesto."
},
"research.step_2": {
"en": "Claude runs web searches on public sources.",
"it": "Claude esegue web search su fonti pubbliche."
},
"research.step_3": {
"en": "It synthesizes a profile with capacity/propensity scores.",
"it": "Sintetizza profilo con capacity/propensity score."
},
"research.step_4": {
"en": "It populates wealth, board, giving, connections.",
"it": "Popola wealth, board, giving, connections."
},
"research.step_5": {
"en": "It saves to the CRM with photo and next-best-action.",
"it": "Salva nel CRM con foto e next-best-action."
},
"research.subtitle": {
"en": "Powered by Claude · automatic web search + fetch · structured JSON output",
"it": "Powered by Claude · web search + fetch automatici · output JSON strutturato"
},
"research.target_corporate": {
"en": "Corporate",
"it": "Corporate"
},
"research.target_corporate_desc": {
"en": "Mid/large companies, family offices, sponsors",
"it": "Aziende mid/large, family office, sponsor"
},
"research.target_examples": {
"en": "Target examples",
"it": "Esempi di target"
},
"research.target_foundation": {
"en": "Foundation",
"it": "Fondazione"
},
"research.target_foundation_desc": {
"en": "Bank/corporate/community foundations, grantmakers (e.g. Cariplo, Compagnia di San Paolo, CON IL SUD)",
"it": "Fondazioni bancarie/d'impresa/comunitarie, enti a bando (es. Cariplo, Compagnia di San Paolo, CON IL SUD)"
},
"research.target_major_donor": {
"en": "Major donor",
"it": "Major donor"
},
"research.target_major_donor_desc": {
"en": "Entrepreneurs, heirs, executives, board members",
"it": "Imprenditori, eredi, executive, board member"
},
"research.th_finished": {
"en": "Finished",
"it": "Concluso"
},
"research.th_started": {
"en": "Started",
"it": "Avviato"
},
"research.th_status": {
"en": "Status",
"it": "Status"
},
"research.th_target": {
"en": "Target",
"it": "Target"
},
"research.title": {
"en": "Prospect Research",
"it": "Prospect Research"
},
"research.type_hint_corporate": {
"en": "(company)",
"it": "(azienda)"
},
"research.type_hint_foundation": {
"en": "(grantmaker)",
"it": "(ente erogatore)"
},
"research.type_hint_individual": {
"en": "(person)",
"it": "(persona)"
},
"research.workspace": {
"en": "Workspace",
"it": "Workspace"
},
"seqdet.body": {
"en": "Email body",
"it": "Corpo email"
},
"seqdet.breadcrumb": {
"en": "Sequence",
"it": "Sequence"
},
"seqdet.confirm_delete": {
"en": "Delete sequence?",
"it": "Eliminare sequence?"
},
"seqdet.created": {
"en": "created",
"it": "creata"
},
"seqdet.days_from_start": {
"en": "days from start",
"it": "giorni dall'inizio"
},
"seqdet.delay_days": {
"en": "Delay (days)",
"it": "Delay (giorni)"
},
"seqdet.delete": {
"en": "Delete",
"it": "Elimina"
},
"seqdet.mark_sent": {
"en": "Mark as sent",
"it": "Segna inviata"
},
"seqdet.open_in_client": {
"en": "Open in client",
"it": "Apri in client"
},
"seqdet.save_step": {
"en": "Save step",
"it": "Salva step"
},
"seqdet.sent": {
"en": "Sent",
"it": "Inviata"
},
"seqdet.step_fallback": {
"en": "step",
"it": "step"
},
"seqdet.step_unit": {
"en": "steps",
"it": "step"
},
"seqdet.subject": {
"en": "Subject",
"it": "Oggetto"
},
"seqdet.title": {
"en": "Sequence",
"it": "Sequence"
},
"seqnew.back": {
"en": "Back",
"it": "Indietro"
},
"seqnew.breadcrumb": {
"en": "Email sequence",
"it": "Sequence email"
},
"seqnew.error_generation": {
"en": "Generation error",
"it": "Errore nella generazione"
},
"seqnew.error_title": {
"en": "Generation error",
"it": "Errore generazione"
},
"seqnew.existing_title": {
"en": "Existing sequences",
"it": "Sequence esistenti"
},
"seqnew.generate": {
"en": "Generate sequence",
"it": "Genera sequence"
},
"seqnew.goal_ask": {
"en": "Ask — sequence leading to a specific request",
"it": "Ask — sequence verso una richiesta specifica"
},
"seqnew.goal_cold_outreach": {
"en": "Cold outreach — first contact through to a meeting",
"it": "Cold outreach — primo contatto fino a meeting"
},
"seqnew.goal_cultivation": {
"en": "Cultivation — build the relationship over time",
"it": "Cultivation — costruisci relazione nel tempo"
},
"seqnew.goal_label": {
"en": "Sequence goal",
"it": "Goal della sequence"
},
"seqnew.goal_reactivation": {
"en": "Reactivation — re-engage a lapsed donor",
"it": "Reactivation — lapsed donor da riattivare"
},
"seqnew.goal_thank_steward": {
"en": "Thank you + stewardship after a gift",
"it": "Thank you + stewardship dopo donazione"
},
"seqnew.heading": {
"en": "Generate email sequence",
"it": "Genera sequence email"
},
"seqnew.loading_status_almost": {
"en": "Almost ready — final steps…",
"it": "Quasi pronta — ultimi step…"
},
"seqnew.loading_status_continue": {
"en": "Continuing: follow-ups and ask…",
"it": "Continuazione: follow-up e ask…"
},
"seqnew.loading_status_done": {
"en": "✓ Sequence ready. Redirecting…",
"it": "✓ Sequence pronta. Reindirizzo…"
},
"seqnew.loading_status_first": {
"en": "Claude is writing the first steps…",
"it": "Claude sta scrivendo i primi step…"
},
"seqnew.loading_status_initial": {
"en": "Starting generation (may take 1–3 minutes for 4 steps).",
"it": "Avvio della generazione (può richiedere 1-3 minuti per 4 step)."
},
"seqnew.loading_status_starting": {
"en": "Starting generation…",
"it": "Avvio della generazione…"
},
"seqnew.loading_title": {
"en": "Claude is generating the sequence…",
"it": "Claude sta generando la sequence…"
},
"seqnew.n_steps_label": {
"en": "Number of steps",
"it": "Numero di step"
},
"seqnew.prospect": {
"en": "Prospect",
"it": "Prospect"
},
"seqnew.retry": {
"en": "Retry",
"it": "Riprova"
},
"seqnew.step_unit": {
"en": "steps",
"it": "step"
},
"seqnew.subtitle": {
"en": "Claude writes a cohesive series of emails (intro → follow-up → ask → steward), spaced over time. All drafts are editable afterward.",
"it": "Claude scrive una serie coerente di email (intro → follow-up → ask → steward), spaziate nel tempo. Tutte le bozze sono editabili dopo."
},
"seqnew.tip_body": {
"en": "Sequences are <em>drafts</em>: no email is sent automatically. Open each step, review it, copy/open it in your email client, and mark it \"sent\" once you've sent it.",
"it": "Le sequence sono <em>bozze</em>: nessuna email viene inviata automaticamente. Apri ogni step, controlla, copia/apri nel tuo client email e marca \"inviata\" quando hai mandato."
},
"seqnew.tip_label": {
"en": "Tip",
"it": "Suggerimento"
},
"seqnew.title": {
"en": "New sequence",
"it": "Nuova sequence"
},
"snip.body": {
"en": "Body",
"it": "Corpo"
},
"snip.body_ph": {
"en": "Reusable text…",
"it": "Testo riusabile…"
},
"snip.cat_ask": {
"en": "Ask / request",
"it": "Ask / richiesta"
},
"snip.cat_closing": {
"en": "Closing / sign-off",
"it": "Chiusura / saluto"
},
"snip.cat_custom": {
"en": "Custom",
"it": "Custom"
},
"snip.cat_followup": {
"en": "Follow-up",
"it": "Follow-up"
},
"snip.cat_intro": {
"en": "Intro / opening",
"it": "Intro / apertura"
},
"snip.category": {
"en": "Category",
"it": "Categoria"
},
"snip.confirm_delete": {
"en": "Delete?",
"it": "Eliminare?"
},
"snip.create": {
"en": "Create snippet",
"it": "Crea snippet"
},
"snip.empty": {
"en": "No snippets yet. Create one to reuse it in the email editor.",
"it": "Nessun snippet. Creane uno per riutilizzarlo nell'editor email."
},
"snip.eyebrow": {
"en": "Tools",
"it": "Strumenti"
},
"snip.library": {
"en": "Library",
"it": "Libreria"
},
"snip.name": {
"en": "Name",
"it": "Nome"
},
"snip.name_ph": {
"en": "e.g. Warm opening",
"it": "es. Apertura caloroso"
},
"snip.new": {
"en": "New snippet",
"it": "Nuovo snippet"
},
"snip.subtitle": {
"en": "Reusable email phrases — openings, closings, asks, boilerplate paragraphs. Insert them in compose via the Snippets menu.",
"it": "Frasi riusabili per le email — aperture, chiusure, ask, paragrafi tipo. Inserisci nello compose con il menù Snippets."
},
"snip.title": {
"en": "Snippets",
"it": "Snippets"
},
"tags.color": {
"en": "Color",
"it": "Colore"
},
"tags.confirm_delete": {
"en": "Delete this tag?",
"it": "Eliminare il tag?"
},
"tags.create": {
"en": "Create tag",
"it": "Crea tag"
},
"tags.description": {
"en": "Description (optional)",
"it": "Descrizione (opz)"
},
"tags.empty": {
"en": "No tags yet.",
"it": "Nessun tag ancora."
},
"tags.existing": {
"en": "Existing tags",
"it": "Tag esistenti"
},
"tags.eyebrow": {
"en": "Tools",
"it": "Strumenti"
},
"tags.name": {
"en": "Name",
"it": "Nome"
},
"tags.name_ph": {
"en": "e.g. Family office",
"it": "es. Family office"
},
"tags.new": {
"en": "New tag",
"it": "Nuovo tag"
},
"tags.prospect": {
"en": "prospects",
"it": "prospect"
},
"tags.subtitle": {
"en": "Reusable labels to segment prospects (e.g. \"Family office\", \"Cuneo\", \"Heirs\", \"Lapsed donor\").",
"it": "Etichette riusabili per segmentare i prospect (es. \"Family office\", \"Cuneo\", \"Eredi\", \"Ex donor\")."
},
"tags.title": {
"en": "Tags",
"it": "Tag"
},
"tasks.all_done": {
"en": "All done",
"it": "Tutto fatto"
},
"tasks.create_task": {
"en": "Create task",
"it": "Crea task"
},
"tasks.delete": {
"en": "Delete",
"it": "Elimina"
},
"tasks.done": {
"en": "Completed",
"it": "Completati"
},
"tasks.empty_hint": {
"en": "No open tasks. Create a new task to organize your cultivation.",
"it": "Nessun task aperto. Crea un nuovo task per organizzare la cultivation."
},
"tasks.field_due": {
"en": "Due date",
"it": "Scadenza"
},
"tasks.field_notes": {
"en": "Notes",
"it": "Note"
},
"tasks.field_priority": {
"en": "Priority",
"it": "Priorità"
},
"tasks.field_prospect": {
"en": "Linked prospect (optional)",
"it": "Prospect collegato (opzionale)"
},
"tasks.field_title": {
"en": "Title",
"it": "Titolo"
},
"tasks.heading": {
"en": "Tasks",
"it": "Tasks"
},
"tasks.mark_done": {
"en": "Mark as done",
"it": "Marca completato"
},
"tasks.new_task": {
"en": "New task",
"it": "Nuovo task"
},
"tasks.no_date": {
"en": "No due date",
"it": "Senza scadenza"
},
"tasks.none": {
"en": "— None —",
"it": "— Nessuno —"
},
"tasks.open": {
"en": "open",
"it": "aperte"
},
"tasks.overdue": {
"en": "Overdue",
"it": "In ritardo"
},
"tasks.priority_high": {
"en": "High",
"it": "Alta"
},
"tasks.priority_low": {
"en": "Low",
"it": "Bassa"
},
"tasks.priority_medium": {
"en": "Medium",
"it": "Media"
},
"tasks.recently_done": {
"en": "Recently completed",
"it": "Recenti completati"
},
"tasks.subtitle": {
"en": "Things to do today and in the next 7 days",
"it": "Cose da fare oggi e nei prossimi 7 giorni"
},
"tasks.title": {
"en": "Tasks",
"it": "Tasks"
},
"tasks.title_placeholder": {
"en": "e.g. Follow-up email to Mario Rossi",
"it": "es. Email follow-up a Mario Rossi"
},
"tasks.today": {
"en": "Today",
"it": "Oggi"
},
"tasks.upcoming": {
"en": "Next 7 days",
"it": "Prossimi 7 giorni"
},
"tasks.workspace": {
"en": "Workspace",
"it": "Workspace"
},
"usage.all_time": {
"en": "All time",
"it": "All time"
},
"usage.available": {
"en": "available",
"it": "disponibili"
},
"usage.by_kind": {
"en": "By operation type",
"it": "Per tipo di operazione"
},
"usage.calls_last_30": {
"en": "Calls in the last 30 days",
"it": "Chiamate ultimi 30 giorni"
},
"usage.chart_calls": {
"en": "Calls",
"it": "Chiamate"
},
"usage.chart_cost": {
"en": "Cost $",
"it": "Costo $"
},
"usage.chart_empty": {
"en": "No calls recorded in the last 30 days.",
"it": "Nessuna chiamata registrata negli ultimi 30 giorni."
},
"usage.chart_unavailable": {
"en": "Chart unavailable (library not loaded).",
"it": "Grafico non disponibile (libreria non caricata)."
},
"usage.col_avg_dur": {
"en": "Avg. duration",
"it": "Durata media"
},
"usage.col_calls": {
"en": "Calls",
"it": "Chiamate"
},
"usage.col_cost": {
"en": "Cost",
"it": "Costo"
},
"usage.col_duration": {
"en": "Duration",
"it": "Durata"
},
"usage.col_prospect": {
"en": "Prospect",
"it": "Prospect"
},
"usage.col_result": {
"en": "Result",
"it": "Esito"
},
"usage.col_tokens": {
"en": "Tokens in/out",
"it": "Token in/out"
},
"usage.col_type": {
"en": "Type",
"it": "Tipo"
},
"usage.col_when": {
"en": "When",
"it": "Quando"
},
"usage.err": {
"en": "err",
"it": "err"
},
"usage.error": {
"en": "error",
"it": "errore"
},
"usage.errors": {
"en": "Errors",
"it": "Errori"
},
"usage.est_cost": {
"en": "Estimated cost",
"it": "Costo stimato"
},
"usage.hunter_quota": {
"en": "Hunter.io quota",
"it": "Quota Hunter.io"
},
"usage.hunter_unavailable": {
"en": "Hunter not configured or unreachable.",
"it": "Hunter non configurato o non raggiungibile."
},
"usage.last_30d": {
"en": "Last 30 days",
"it": "Ultimi 30gg"
},
"usage.last_7d": {
"en": "Last 7 days",
"it": "Ultimi 7gg"
},
"usage.no_calls": {
"en": "No calls recorded",
"it": "Nessuna chiamata registrata"
},
"usage.no_data": {
"en": "No data",
"it": "Nessun dato"
},
"usage.no_prospect_usage": {
"en": "No usage tied to a prospect",
"it": "Nessun consumo legato a prospect"
},
"usage.of_total": {
"en": "of total",
"it": "sul totale"
},
"usage.ok": {
"en": "OK",
"it": "OK"
},
"usage.plan": {
"en": "Plan",
"it": "Piano"
},
"usage.recent_events": {
"en": "Last 30 events",
"it": "Ultimi 30 eventi"
},
"usage.records": {
"en": "records",
"it": "record"
},
"usage.reset": {
"en": "Reset",
"it": "Reset"
},
"usage.searches_used": {
"en": "searches used",
"it": "searches usate"
},
"usage.subtitle": {
"en": "Claude calls made by the CRM, estimated cost, tokens consumed, average duration and errors.",
"it": "Chiamate Claude effettuate dal CRM, costi stimati, token consumati, durata media e errori."
},
"usage.title": {
"en": "AI usage",
"it": "Consumo AI"
},
"usage.top_prospects": {
"en": "Top prospects by usage",
"it": "Top prospect per consumo"
},
"usage.total_calls": {
"en": "Total calls",
"it": "Totale chiamate"
},
"usage.total_usd": {
"en": "Total USD via CLI",
"it": "Tot. USD da CLI"
},
"welcome.ask_help": {
"en": "Claude will use these amounts to suggest the starting ask for each prospect.",
"it": "Claude userà questi importi per suggerire l'ask di partenza per ogni prospect."
},
"welcome.field_ask_corporate": {
"en": "Corporate donor (EUR)",
"it": "Donatore corporate (EUR)"
},
"welcome.field_ask_individual": {
"en": "Individual donor (EUR)",
"it": "Donatore individuale (EUR)"
},
"welcome.field_causes": {
"en": "Causes you support (comma-separated)",
"it": "Cause che sostenete (separate da virgola)"
},
"welcome.field_causes_help": {
"en": "Those who have supported similar causes in the past will get a higher affinity score.",
"it": "Chi nel suo passato ha sostenuto cause simili otterrà un affinity score più alto."
},
"welcome.field_causes_ph": {
"en": "e.g. end-of-life rights, civil rights, scientific research, LGBTQI+",
"it": "es. fine vita, diritti civili, ricerca scientifica, LGBTQI+"
},
"welcome.field_legal_form": {
"en": "Legal form",
"it": "Forma giuridica"
},
"welcome.field_mission": {
"en": "Mission in 1-2 sentences",
"it": "Mission in 1-2 frasi"
},
"welcome.field_mission_ph": {
"en": "E.g.: we promote civil liberties, in particular the right to end-of-life choices and freedom of scientific research.",
"it": "Es: promuoviamo le libertà civili, in particolare il diritto al fine vita e la libertà di ricerca scientifica."
},
"welcome.field_org_name": {
"en": "Organization name",
"it": "Nome organizzazione"
},
"welcome.field_org_name_ph": {
"en": "e.g. Associazione Luca Coscioni",
"it": "es. Associazione Luca Coscioni"
},
"welcome.intro": {
"en": "Before you start, tell us a couple of things about your organization. It takes just 60 seconds — Claude will use this information to calibrate every prospect research to your context.",
"it": "Prima di iniziare, raccontaci due cose sulla tua organizzazione. Bastano 60 secondi — Claude userà queste informazioni per calibrare ogni ricerca prospect sul tuo contesto."
},
"welcome.optional": {
"en": "optional",
"it": "opzionali"
},
"welcome.refine_link": {
"en": "My org",
"it": "La mia org"
},
"welcome.refine_post": {
"en": "page. The more details you add (programs, past partnerships, ideal donor profile, exclusion criteria), the better Claude will work for you.",
"it": "Più dettagli aggiungi (programmi, partnership storiche, profilo donor ideale, criteri esclusione), più Claude lavorerà bene per te."
},
"welcome.refine_pre": {
"en": "everything from the",
"it": "tutto dalla pagina"
},
"welcome.refine_strong": {
"en": "You can always refine",
"it": "Potrai sempre rifinire"
},
"welcome.save_start": {
"en": "Save and start",
"it": "Salva e inizia"
},
"welcome.select_placeholder": {
"en": "— Select —",
"it": "— Seleziona —"
},
"welcome.setup_badge": {
"en": "Initial setup",
"it": "Setup iniziale"
},
"welcome.skip": {
"en": "Skip for now",
"it": "Salta per ora"
},
"welcome.step1_title": {
"en": "Identity",
"it": "Identità"
},
"welcome.step2_title": {
"en": "Mission & causes",
"it": "Mission & cause"
},
"welcome.step3_title": {
"en": "Typical ask amounts",
"it": "Ask amount tipici"
},
"welcome.title": {
"en": "Welcome to Forager",
"it": "Benvenuto in Forager"
}
}
